import type { ConnectedAccount, ContactPerson } from "../contracts";

export const CONNECTED_ACCOUNTS: readonly ConnectedAccount[] = [
  {
    id: "acc_gmail",
    service: "Gmail",
    account: "dev@autodo.ai",
    connectionState: "CONNECTED",
    scopes: ["gmail.readonly", "gmail.modify", "gmail.send"],
    capabilities: ["read", "search", "draft", "send"],
    lastSync: "May 27, 2026 10:32 AM",
    health: "HEALTHY",
    authType: "OAuth2",
    expires: "2026-06-27 (Auto-refresh active)",
  },
  {
    id: "acc_cal",
    service: "Google Calendar",
    account: "dev@autodo.ai",
    connectionState: "CONNECTED",
    scopes: ["calendar.readonly", "calendar.events"],
    capabilities: ["read_events", "create_events"],
    lastSync: "May 27, 2026 10:30 AM",
    health: "HEALTHY",
    authType: "OAuth2",
    expires: "2026-06-27",
  },
  {
    id: "acc_contacts",
    service: "Google Contacts",
    account: "dev@autodo.ai",
    connectionState: "CONNECTED",
    scopes: ["contacts.readonly"],
    capabilities: ["resolve_contact"],
    lastSync: "May 27, 2026 08:00 AM",
    health: "HEALTHY",
    authType: "OAuth2",
    expires: "2026-06-27",
  },
  {
    id: "acc_github",
    service: "GitHub",
    account: "nelson1869-ai",
    connectionState: "CONNECTED",
    scopes: ["repo:read", "issues:write"],
    capabilities: ["read_repo", "create_issue"],
    lastSync: "May 27, 2026 09:00 AM",
    health: "HEALTHY",
    authType: "OAuth2",
    expires: "Never",
  },
];

export const CONTACTS_PEOPLE: readonly ContactPerson[] = [
  {
    id: "per_01",
    name: "John Doe",
    aliases: ["John", "JD", "John Partner"],
    email: "john@partner.com",
    phone: "+1-555-0199",
    organization: "Acme Partners Inc.",
    relationship: "Partner",
    calendarIdentity: "john@partner.com",
    source: "Google Contacts",
    confidence: 0.98,
  },
  {
    id: "per_02",
    name: "Sarah Connor (HR)",
    aliases: ["HR", "Payroll", "Sarah"],
    email: "hr@company.com",
    organization: "Company HR Corp",
    relationship: "Trusted Team",
    calendarIdentity: "hr@company.com",
    source: "Gmail Headers",
    confidence: 0.95,
  },
  {
    id: "per_03",
    name: "Finance Department",
    aliases: ["Finance", "Billing", "Accounts"],
    email: "finance@company.com",
    organization: "Company Finance",
    relationship: "Trusted Team",
    calendarIdentity: "finance@company.com",
    source: "Gmail Headers",
    confidence: 0.92,
  },
];
