import type { PipelineStep, SimulatedRunSnapshot } from "../contracts";
import { GMAIL_SIMULATION } from "../gmail-data";
import { RAG_SIMULATION } from "../rag";

export const PIPELINE_STEPS: readonly PipelineStep[] = [
  {
    id: 1,
    name: "Input / Cue",
    layerKey: "cue",
    responsibility:
      "Ingress gateway boundary — receive raw cue/event from Chat, Manual Run, Schedule, Webhook, or MCP",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason: "HTTP POST payload accepted at ingress with trace ID (4ms).",
    provenance: "OBSERVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.120",
    completedAt: "10:32:11.124",
    spanId: "spn_cue_00129",
    previousLayer: "Ingress Trigger (HTTP POST /api/runs/create [OBSERVED])",
    nextLayer: "Layer 2 — Perception / Parsing",
    inputContract: "RawHttpRequestPayload (HTTP Ingress)",
    outputContract: "UnparsedCueEvent",
    owns: [
      "Ingress timestamping",
      "Trace correlation header binding",
      "Raw body extraction",
    ],
    doesNotOwn: [
      "Semantic parsing",
      "Sanitization",
      "AI reasoning",
      "Authorization",
    ],
    internalFlow: [
      { step: "Ingress HTTP handshake", durationMs: 1.2 },
      { step: "Trace ID attachment", durationMs: 1.0 },
      { step: "Queue dispatch to Perception", durationMs: 1.8 },
    ],
    inputData: {
      httpMethod: "POST",
      path: "/api/runs/create",
      clientIp: "127.0.0.1",
      headers: { "x-trace-id": "trc_autodo_20260527_98a" },
      rawText: "Summarize unread important emails from today from Gmail.",
      source: "Manual Run",
    },
    outputData: {
      cueId: "cue_00129_raw",
      source: "manual_web_trigger",
      rawPrompt: "Summarize unread important emails from today from Gmail.",
      receivedAt: "2026-05-27T10:32:11.120Z",
    },
    contractDiff: [
      {
        field: "cueId",
        type: "ADDED",
        outputValue: "cue_00129_raw",
        note: "Ingress event tracked",
      },
      {
        field: "traceId",
        type: "ADDED",
        outputValue: "trc_autodo_20260527_98a",
        note: "Distributed trace attached",
      },
    ],
    expectedVsActual: {
      expected: "UnparsedCueEvent with non-empty payload and trace ID",
      actual: "UnparsedCueEvent (54 chars, trace attached)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: 'HTTP POST Body: "Summarize..."',
        fromType: "OBSERVED",
        transform: "Ingress Buffer",
        to: "UnparsedCueEvent (cue_00129_raw)",
        toType: "DERIVED",
        destination: "Layer 2 — Perception / Parsing",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Ingress Body Non-Empty",
        description: "Prompt length 54 chars",
        status: "PASS",
      },
      {
        checkName: "Trace Context Bound",
        description: "Trace ID attached cleanly",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "HTTP Handshake", durationMs: 1.2, percentage: 30.0 },
      { operation: "Trace Context Binding", durationMs: 1.0, percentage: 25.0 },
      { operation: "Dispatch Queueing", durationMs: 1.8, percentage: 45.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.8,
      heapDeltaKb: 2.1,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:11.120",
        level: "INFO",
        event: "cue.received",
        metadata: "Prompt received at ingress (54 chars)",
      },
    ],
    rawJson: {
      layerId: 1,
      layerKey: "cue",
      status: "success",
      cueId: "cue_00129_raw",
    },
  },
  {
    id: 2,
    name: "Perception / Parsing",
    layerKey: "perceive",
    responsibility:
      "Sanitize untrusted input, parse AST, extract entities, resolve timezone ('today' -> UTC window)",
    durationMs: 8,
    status: "success",
    health: "healthy",
    healthReason:
      "Zod schema validated. Timezone resolved to Asia/Manila (UTC window).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.124",
    completedAt: "10:32:11.132",
    spanId: "spn_prc_00129",
    parentSpanId: "spn_cue_00129",
    previousLayer: "Layer 1 — Input / Cue",
    nextLayer: "Layer 3 — Context Build",
    inputContract: "UnparsedCueEvent",
    outputContract: "CanonicalCommand (Schema v1.2)",
    owns: [
      "Prompt sanitization",
      "Temporal resolution",
      "Intent classification",
      "Canonical schema assembly",
    ],
    doesNotOwn: [
      "Session token checks",
      "AI reasoning",
      "Granting execution authorization",
    ],
    internalFlow: [
      { step: "Zod Schema Validation", durationMs: 1.5 },
      { step: "AST Tokenization & Sanitization", durationMs: 2.5 },
      { step: "Temporal Resolution (Asia/Manila)", durationMs: 4.0 },
    ],
    inputData: {
      rawPrompt: "Summarize unread important emails from today from Gmail.",
      locale: "en-US",
      timezone: "Asia/Manila",
    },
    outputData: {
      commandId: "cmd_cue_20260527_00129",
      intent: "gmail.summarize_unread_important",
      requestedScope: "read_only",
      temporalRange: {
        utcStart: "2026-05-26T16:00:00Z",
        utcEnd: "2026-05-27T15:59:59Z",
      },
    },
    contractDiff: [
      {
        field: "commandId",
        type: "ADDED",
        outputValue: "cmd_cue_20260527_00129",
        note: "Canonical command assembled",
      },
      {
        field: "intent",
        type: "ADDED",
        outputValue: "gmail.summarize_unread_important",
        note: "Normalized intent extracted",
      },
      {
        field: "requestedScope",
        type: "ADDED",
        outputValue: "read_only",
        note: "Non-authoritative scope inferred",
      },
    ],
    expectedVsActual: {
      expected:
        "CanonicalCommand with normalized intent and UTC temporal window",
      actual: "CanonicalCommand (cmd_cue_20260527_00129) valid v1.2",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: 'Raw "today"',
        fromType: "OBSERVED",
        transform: "Timezone Engine (Asia/Manila)",
        to: "UTC Window (2026-05-26T16:00Z to 2026-05-27T15:59Z)",
        toType: "DERIVED",
        destination: "Layer 3 — Context Build",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Sanitization Passed",
        description: "Zero prompt injection vectors detected",
        status: "PASS",
      },
      {
        checkName: "Schema Validated",
        description: "Zod CanonicalCommandSchema v1.2 PASS",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Schema Validation", durationMs: 1.5, percentage: 18.8 },
      { operation: "AST Tokenization", durationMs: 2.5, percentage: 31.2 },
      { operation: "Temporal Resolution", durationMs: 4.0, percentage: 50.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.0,
      heapDeltaKb: 2.0,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.4,
    },
    layerLogs: [
      {
        timestamp: "10:32:11.128",
        level: "INFO",
        event: "perceive.sanitized",
        metadata: "Canonical command cmd_cue_20260527_00129 assembled",
      },
    ],
    rawJson: {
      layerId: 2,
      layerKey: "perceive",
      status: "success",
      commandId: "cmd_cue_20260527_00129",
    },
  },
  {
    id: 3,
    name: "Context Build",
    layerKey: "build_context",
    responsibility:
      "Assemble User Goal, Owner Context, Timezone, Connected Accounts, Tool & MCP Availability, Policy Bounds, Token Budget",
    durationMs: 31,
    status: "success",
    health: "healthy",
    healthReason:
      "Session state & active scopes loaded cleanly in 31ms (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.132",
    completedAt: "10:32:11.163",
    spanId: "spn_ctx_00129",
    parentSpanId: "spn_prc_00129",
    previousLayer: "Layer 2 — Perception / Parsing",
    nextLayer: "Layer 4 — Retrieval / Memory",
    inputContract: "CanonicalCommand",
    outputContract: "ExecutionContextBundle",
    owns: [
      "Session lookup",
      "Workspace boundary check",
      "Token readiness audit",
      "Final Context preview assembly",
    ],
    doesNotOwn: ["AI reasoning", "External API calls", "Policy decisions"],
    internalFlow: [
      { step: "Load session state", durationMs: 10.2 },
      { step: "Inspect workspace scopes", durationMs: 12.0 },
      { step: "Package context bundle", durationMs: 8.8 },
    ],
    inputData: {
      commandId: "cmd_cue_20260527_00129",
      userId: "usr_dev_001",
      workspaceId: "ws_autodo_01",
    },
    outputData: {
      role: "Developer",
      activeTokens: 2,
      contextSizeKb: 14.2,
      tokenBudget: 2048,
      nextDestination: "Layer 4 — Retrieval / Memory",
    },
    contractDiff: [
      {
        field: "userProfile",
        type: "ADDED",
        outputValue: "usr_dev_001 (Role: Developer)",
        note: "Session context attached",
      },
      {
        field: "activeTokens",
        type: "ADDED",
        outputValue: "Gmail OAuth2 token attached",
        note: "Integration tokens ready",
      },
      {
        field: "mcpServersReady",
        type: "ADDED",
        outputValue: "2 MCP Servers available",
        note: "Filesystem & Fetch servers attached",
      },
    ],
    expectedVsActual: {
      expected: "ExecutionContextBundle with active integration scopes",
      actual: "ExecutionContextBundle (14.2 KB) ready",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "CanonicalCommand (cmd_cue)",
        fromType: "DERIVED",
        transform: "Session Repository Lookup",
        to: "ExecutionContextBundle (14.2 KB)",
        toType: "DERIVED",
        destination: "Layer 4 — Retrieval / Memory",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Session Active",
        description: "Developer session authenticated",
        status: "PASS",
      },
      {
        checkName: "Tokens Attached",
        description: "2 integration tokens verified",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Session DB Lookup", durationMs: 10.2, percentage: 32.9 },
      { operation: "Scope Inspection", durationMs: 12.0, percentage: 38.7 },
      { operation: "Bundle Packaging", durationMs: 8.8, percentage: 28.4 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 4.2,
      heapDeltaKb: 14.2,
      eventLoopLagMs: 0.03,
      memoryAllocatedKb: 28.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:11.139",
        level: "INFO",
        event: "context.init",
        metadata: "Reading session usr_dev_001",
      },
      {
        timestamp: "10:32:11.163",
        level: "SUCCESS",
        event: "context.completed",
        metadata: "Bundle packaged (14.2 KB)",
      },
    ],
    rawJson: {
      layerId: 3,
      layerKey: "build_context",
      status: "success",
      contextSizeKb: 14.2,
    },
  },
  {
    id: 4,
    name: "Retrieval / Memory",
    layerKey: "retrieve_memory",
    responsibility:
      "RAG & Memory retrieval — search verified preference memories via pgvector similarity (MEMORY != PERMISSION)",
    durationMs: 43,
    status: "success",
    health: "healthy",
    healthReason:
      "RAG required: YES. Strategy: PERSONAL_MEMORY + VECTOR (pgvector). 2 preference memories retrieved (SIMULATED).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.163",
    completedAt: "10:32:11.206",
    spanId: "spn_mem_00129",
    parentSpanId: "spn_ctx_00129",
    previousLayer: "Layer 3 — Context Build",
    nextLayer: "Layer 5 — AI Reasoning",
    inputContract: "ExecutionContextBundle",
    outputContract: "MemoryEnrichedContext",
    owns: [
      "RAG necessity decision",
      "Vector similarity search",
      "Memory relevance thresholding",
    ],
    doesNotOwn: [
      "Granting execution permission based on memory (MEMORY != PERMISSION)",
    ],
    internalFlow: [
      { step: "Evaluate RAG requirement (YES)", durationMs: 2.0 },
      { step: "Generate query embedding", durationMs: 16.0 },
      { step: "pgvector similarity scan", durationMs: 20.5 },
      { step: "Filter top-K memories", durationMs: 4.5 },
    ],
    inputData: RAG_SIMULATION.request,
    outputData: RAG_SIMULATION.output,
    contractDiff: [
      {
        field: "retrievedMemories",
        type: "ADDED",
        outputValue: "2 matched memory fragments",
        note: "Attached to reasoning context",
      },
      {
        field: "safetyBoundary",
        type: "PRESERVED",
        outputValue: "Memory does NOT grant execution permissions",
        note: "Invariant enforced",
      },
    ],
    expectedVsActual: {
      expected: "MemoryEnrichedContext with top-K memories",
      actual: "MemoryEnrichedContext (2 memories attached)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Email summary query",
        fromType: "DERIVED",
        transform: "Vector Cosine Search (pgvector)",
        to: "Memory Fragment #MEM-012 (Concise bullets)",
        toType: "DERIVED",
        destination: "Layer 5 — AI Reasoning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Memory != Permission",
        description: "Retrieved memory does not override policy",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "RAG Check", durationMs: 2.0, percentage: 4.6 },
      {
        operation: "Embedding Calculation",
        durationMs: 16.0,
        percentage: 37.2,
      },
      { operation: "Vector Index Scan", durationMs: 20.5, percentage: 47.7 },
      { operation: "Memory Filtering", durationMs: 4.5, percentage: 10.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 6.1,
      heapDeltaKb: 8.5,
      eventLoopLagMs: 0.04,
      memoryAllocatedKb: 34.2,
    },
    layerLogs: [
      {
        timestamp: "10:32:11.182",
        level: "SUCCESS",
        event: "memory.completed",
        metadata: "2 memories attached to context",
      },
    ],
    rawJson: {
      layerId: 4,
      layerKey: "retrieve_memory",
      status: "success",
      matchedCount: 2,
    },
  },
  {
    id: 5,
    name: "AI Reasoning",
    layerKey: "reason",
    responsibility:
      "Generate structured execution plan & tool proposals via Gemini JSON contract (AI CHOICE != PERMISSION)",
    durationMs: 781,
    status: "success",
    health: "slow",
    healthReason:
      "Highest pipeline latency (781ms, 41.3% of active execution time). Consumes majority of critical path.",
    provenance: "SIMULATED",
    isCriticalPath: true,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.206",
    completedAt: "10:32:11.987",
    spanId: "spn_ai_00129",
    parentSpanId: "spn_mem_00129",
    previousLayer: "Layer 4 — Retrieval / Memory",
    nextLayer: "Layer 6 — Candidate Generation",
    inputContract: "ModelPromptPayload",
    outputContract: "StructuredReasoningPlan",
    owns: [
      "Prompt serialization",
      "AI API roundtrip",
      "Structured output parsing",
      "Model Router selection",
    ],
    doesNotOwn: [
      "Private chain-of-thought exposure",
      "Granting execution authorization (AI CHOICE != PERMISSION)",
    ],
    internalFlow: [
      { step: "Construct model prompt", durationMs: 12.0 },
      { step: "AI API roundtrip (SIMULATED)", durationMs: 750.0 },
      { step: "Parse structured plan", durationMs: 19.0 },
    ],
    inputData: {
      model: "gemini-2.5-pro",
      routerReason: "Complex planning task requires strong structured output",
      temperature: 0.2,
      topP: 1.0,
      maxTokens: 2048,
    },
    outputData: {
      totalTokens: 12342,
      planStepsCount: 5,
      proposedAction: "gmail.list_messages",
    },
    contractDiff: [
      {
        field: "structuredPlan",
        type: "ADDED",
        outputValue: "5-step plan formulated",
        note: "Parsed from model JSON response",
      },
      {
        field: "proposedAction",
        type: "ADDED",
        outputValue: "gmail.list_messages",
        note: "Primary action recommendation",
      },
      {
        field: "chainOfThought",
        type: "REMOVED",
        outputValue: "[KEPT OFF APPLICATION STATE]",
        note: "Private model thoughts not persisted",
      },
    ],
    expectedVsActual: {
      expected: "StructuredReasoningPlan with valid schema output",
      actual: "StructuredReasoningPlan (5 steps, 12,342 tokens)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Prompt + Memory Bundle",
        fromType: "DERIVED",
        transform: "Gemini 2.5 Pro JSON Mode",
        to: "Structured Plan (gmail.list_messages proposal)",
        toType: "SIMULATED",
        destination: "Layer 6 — Candidate Generation",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Schema Match",
        description: "Model response matches output schema",
        status: "PASS",
      },
      {
        checkName: "Zero CoT Leakage",
        description: "Private model thoughts kept off application telemetry",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Prompt Construction", durationMs: 12.0, percentage: 1.5 },
      {
        operation: "API Network Roundtrip",
        durationMs: 750.0,
        percentage: 96.0,
      },
      { operation: "Plan Validation", durationMs: 19.0, percentage: 2.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 14.5,
      heapDeltaKb: 22.0,
      eventLoopLagMs: 0.05,
      memoryAllocatedKb: 89.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.003",
        level: "SUCCESS",
        event: "ai.completed",
        metadata: "Structured plan generated (12,342 tokens [SIMULATED])",
      },
    ],
    rawJson: {
      layerId: 5,
      layerKey: "reason",
      status: "success",
      tokens: 12342,
    },
  },
  {
    id: 6,
    name: "Candidate Generation",
    layerKey: "generate_candidates",
    responsibility:
      "Instantiate typed candidate actions and validate schema signatures for each proposal",
    durationMs: 112,
    status: "success",
    health: "healthy",
    healthReason:
      "Generated 4 candidate actions conforming to registered tool contracts (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:11.987",
    completedAt: "10:32:12.099",
    spanId: "spn_cand_00129",
    parentSpanId: "spn_ai_00129",
    previousLayer: "Layer 5 — AI Reasoning",
    nextLayer: "Layer 7 — Scoring & Ranking",
    inputContract: "StructuredReasoningPlan",
    outputContract: "CandidateActionSet",
    owns: ["Action instantiation", "Argument schema validation per candidate"],
    doesNotOwn: ["Scoring", "Policy evaluation"],
    internalFlow: [
      { step: "Extract tool proposals", durationMs: 40.0 },
      { step: "Validate candidate arguments", durationMs: 72.0 },
    ],
    inputData: { plan: "Summarize unread important emails" },
    outputData: { candidatesCount: 4, topCandidate: "gmail.list_messages" },
    contractDiff: [
      {
        field: "candidates",
        type: "ADDED",
        outputValue: "4 candidate actions (list, search, get, draft)",
        note: "Instantiated with typed payloads",
      },
    ],
    expectedVsActual: {
      expected: "CandidateActionSet with validated tool parameter schemas",
      actual: "CandidateActionSet (4 typed candidates ready)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Structured Plan proposal",
        fromType: "SIMULATED",
        transform: "Tool Contract Builder",
        to: "4 CandidateAction instances",
        toType: "DERIVED",
        destination: "Layer 7 — Scoring & Ranking",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Candidate Signatures Valid",
        description: "Arguments match Gmail API schema",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Proposal Extraction", durationMs: 40.0, percentage: 35.7 },
      { operation: "Schema Validation", durationMs: 72.0, percentage: 64.3 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 8.2,
      heapDeltaKb: 12.4,
      eventLoopLagMs: 0.02,
      memoryAllocatedKb: 45.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.125",
        level: "SUCCESS",
        event: "candidate.generated",
        metadata: "4 candidates prepared",
      },
    ],
    rawJson: {
      layerId: 6,
      layerKey: "generate_candidates",
      status: "success",
      count: 4,
    },
  },
  {
    id: 7,
    name: "Scoring & Ranking",
    layerKey: "score",
    responsibility:
      "Evaluate candidate scores deterministically and rank proposals (HIGH SCORE != PERMISSION)",
    durationMs: 18,
    status: "success",
    health: "healthy",
    healthReason:
      "Heuristic scoring selected list_messages (0.94) as top candidate (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.099",
    completedAt: "10:32:12.117",
    spanId: "spn_score_00129",
    parentSpanId: "spn_cand_00129",
    previousLayer: "Layer 6 — Candidate Generation",
    nextLayer: "Layer 8 — Grounding",
    inputContract: "CandidateActionSet",
    outputContract: "RankedCandidateProposal",
    owns: ["Deterministic ranking weights", "Selection threshold check"],
    doesNotOwn: ["Granting execution permission (HIGH SCORE != PERMISSION)"],
    internalFlow: [
      { step: "Evaluate heuristics", durationMs: 8.0 },
      { step: "Rank & sort candidates", durationMs: 10.0 },
    ],
    inputData: { candidatesEvaluated: 4 },
    outputData: { topScore: 0.94, selectedCandidate: "gmail.list_messages" },
    contractDiff: [
      {
        field: "candidateScores",
        type: "ADDED",
        outputValue: "list: 0.94, search: 0.82, get: 0.68, draft: 0.45",
        note: "Calculated heuristics",
      },
      {
        field: "status",
        type: "CHANGED",
        inputValue: "unranked",
        outputValue: "list_messages = chosen",
        note: "Top proposal selected",
      },
    ],
    expectedVsActual: {
      expected: "RankedCandidateProposal with highest scoring candidate",
      actual: "RankedCandidateProposal (Score 0.94, Chosen: list_messages)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "4 CandidateAction instances",
        fromType: "DERIVED",
        transform: "Deterministic Scoring Matrix",
        to: "Top proposal (list_messages, score: 0.94)",
        toType: "DERIVED",
        destination: "Layer 8 — Grounding",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Score != Permission",
        description: "Score 0.94 requires Grounding & Policy checks",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Heuristic Evaluation", durationMs: 8.0, percentage: 44.4 },
      { operation: "Ranking Sort", durationMs: 10.0, percentage: 55.6 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 2.1,
      heapDeltaKb: 3.2,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 14.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.343",
        level: "SUCCESS",
        event: "scoring.completed",
        metadata: "Top score: 0.94",
      },
    ],
    rawJson: {
      layerId: 7,
      layerKey: "score",
      status: "success",
      topScore: 0.94,
    },
  },
  {
    id: 8,
    name: "Grounding",
    layerKey: "ground",
    responsibility:
      "Verify candidate against live source contracts, token scopes, and endpoint schema (GROUNDING != PERMISSION)",
    durationMs: 206,
    status: "success",
    health: "healthy",
    healthReason:
      "5/5 source grounding checks passed without conflicts (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: true,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.117",
    completedAt: "10:32:12.323",
    spanId: "spn_gnd_00129",
    parentSpanId: "spn_score_00129",
    previousLayer: "Layer 7 — Scoring & Ranking",
    nextLayer: "Layer 9 — Policy / Safety",
    inputContract: "RankedCandidateProposal",
    outputContract: "GroundedProposalWithEvidence",
    owns: [
      "Source authentication check",
      "Endpoint reachability",
      "Quota freshness",
    ],
    doesNotOwn: ["Policy authorization decisions"],
    internalFlow: [
      { step: "OAuth2 scope check", durationMs: 65.0 },
      { step: "API contract validation", durationMs: 85.0 },
      { step: "Quota & rate limit audit", durationMs: 56.0 },
    ],
    inputData: {
      targetService: "api.gmail.com",
      requiredScope: "gmail.readonly",
    },
    outputData: { checksPassed: 5, conflictsCount: 0, isGrounded: true },
    contractDiff: [
      {
        field: "groundingEvidence",
        type: "ADDED",
        outputValue: "5 evidence assertions attached",
        note: "Verified against OAuth2 scopes",
      },
      {
        field: "isGrounded",
        type: "ADDED",
        outputValue: "true",
        note: "Ready for policy evaluation",
      },
    ],
    expectedVsActual: {
      expected: "GroundedProposalWithEvidence with zero evidence conflicts",
      actual: "GroundedProposalWithEvidence (5/5 passed, 0 conflicts)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Ranked proposal (list_messages)",
        fromType: "DERIVED",
        transform: "Live Scope & Contract Verifier",
        to: "Grounded Proposal with 5 Evidence Assertions",
        toType: "DERIVED",
        destination: "Layer 9 — Policy / Safety",
      },
    ],
    evidenceChecks: [
      {
        checkName: "OAuth2 Scope Valid",
        description: "gmail.readonly simulated active",
        status: "PASS",
      },
      {
        checkName: "Endpoint Schema Match",
        description: "v1/users/me/messages verified",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "OAuth2 Scope Verification",
        durationMs: 65.0,
        percentage: 31.5,
      },
      {
        operation: "Contract Schema Validation",
        durationMs: 85.0,
        percentage: 41.3,
      },
      { operation: "Quota Audit", durationMs: 56.0, percentage: 27.2 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 7.4,
      heapDeltaKb: 9.1,
      eventLoopLagMs: 0.02,
      memoryAllocatedKb: 42.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.561",
        level: "SUCCESS",
        event: "grounding.completed",
        metadata: "5/5 evidence points verified",
      },
    ],
    rawJson: {
      layerId: 8,
      layerKey: "ground",
      status: "success",
      checksPassed: 5,
    },
  },
  {
    id: 9,
    name: "Policy / Safety",
    layerKey: "policy",
    responsibility:
      "Evaluate deterministic RBAC security policy OUTSIDE LLM boundary (POLICY IS EXTERNAL TO LLM)",
    durationMs: 14,
    status: "success",
    health: "healthy",
    healthReason:
      "Evaluated RULE_READONLY_AUTO_APPROVE (ALLOW). Zero destructive operations (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.323",
    completedAt: "10:32:12.337",
    spanId: "spn_pol_00129",
    parentSpanId: "spn_gnd_00129",
    previousLayer: "Layer 8 — Grounding",
    nextLayer: "Layer 10 — Authorization",
    inputContract: "GroundedProposalWithEvidence",
    outputContract: "PolicyDecisionEnvelope",
    owns: [
      "Deterministic policy evaluation outside LLM",
      "Human gate determination",
      "Destructive action scanning",
    ],
    doesNotOwn: ["AI planning", "Tool execution"],
    internalFlow: [
      { step: "Evaluate RBAC rules", durationMs: 6.0 },
      { step: "Check destructive flags", durationMs: 4.0 },
      { step: "Formulate policy decision", durationMs: 4.0 },
    ],
    inputData: {
      action: "gmail.list_messages",
      scope: "read_only",
      destructive: false,
    },
    outputData: {
      decision: "ALLOW",
      rule: "POLICY_READ_ONLY_DEFAULT_PERMIT",
      humanApprovalRequired: false,
    },
    contractDiff: [
      {
        field: "policyDecision",
        type: "ADDED",
        outputValue: "ALLOW (Rule: POLICY_READ_ONLY_DEFAULT_PERMIT)",
        note: "Evaluated outside LLM",
      },
      {
        field: "humanGateRequired",
        type: "ADDED",
        outputValue: "false",
        note: "Non-destructive read-only command",
      },
    ],
    expectedVsActual: {
      expected:
        "PolicyDecisionEnvelope with explicit ALLOW/DENY/REQUIRE_APPROVAL",
      actual: "PolicyDecisionEnvelope (Decision: ALLOW, Rule matched)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Grounded proposal",
        fromType: "DERIVED",
        transform: "Deterministic Policy Engine (External to LLM)",
        to: "Policy Decision: ALLOW",
        toType: "DERIVED",
        destination: "Layer 10 — Authorization",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Policy Outside LLM",
        description: "Rule evaluated deterministically",
        status: "PASS",
      },
      {
        checkName: "Read-Only Auto Permit",
        description: "Non-destructive actions allowed by default",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "RBAC Rule Evaluation", durationMs: 6.0, percentage: 42.9 },
      {
        operation: "Destructive Action Scanner",
        durationMs: 4.0,
        percentage: 28.6,
      },
      { operation: "Decision Assembly", durationMs: 4.0, percentage: 28.6 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.5,
      heapDeltaKb: 2.1,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 12.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.579",
        level: "SUCCESS",
        event: "policy.passed",
        metadata: "Decision: ALLOW",
      },
    ],
    rawJson: {
      layerId: 9,
      layerKey: "policy",
      status: "success",
      decision: "ALLOW",
    },
  },
  {
    id: 10,
    name: "Authorization",
    layerKey: "authorize",
    responsibility:
      "Issue time-bounded cryptographic lease token for execution worker (AUTHORIZATION IS THE GATE)",
    durationMs: 9,
    status: "success",
    health: "healthy",
    healthReason:
      "60s execution authorization lease envelope issued (PLANNED / MOCK).",
    provenance: "PLANNED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.337",
    completedAt: "10:32:12.346",
    spanId: "spn_auth_00129",
    parentSpanId: "spn_pol_00129",
    previousLayer: "Layer 9 — Policy / Safety",
    nextLayer: "Layer 11 — Planning",
    inputContract: "PolicyDecisionEnvelope",
    outputContract: "SignedExecutionLease [PLANNED ARCHITECTURE / MOCK]",
    owns: [
      "Cryptographic signing [PLANNED]",
      "Execution lease TTL enforcement [PLANNED]",
    ],
    doesNotOwn: ["Tool network dispatch", "AI reasoning"],
    internalFlow: [
      { step: "Generate lease signature simulation", durationMs: 5.0 },
      { step: "Bind correlation ID & TTL", durationMs: 4.0 },
    ],
    inputData: { executor: "worker_agent_01", leaseSeconds: 60 },
    outputData: {
      leaseStatus: "APPROVED (SIMULATED)",
      expiresAt: "2026-05-27T10:34:53Z",
    },
    contractDiff: [
      {
        field: "authorizationStatus",
        type: "ADDED",
        outputValue: "AUTHORIZED",
        note: "Permission granted for worker execution",
      },
      {
        field: "leaseEnvelope",
        type: "ADDED",
        outputValue: "TTL 60s (Expires 10:34:53Z)",
        note: "Simulated cryptographic lease",
      },
    ],
    expectedVsActual: {
      expected: "SignedExecutionLease with bound correlation ID and 60s TTL",
      actual: "SignedExecutionLease (APPROVED, 60s lease [PLANNED / MOCK])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Policy Decision: ALLOW",
        fromType: "DERIVED",
        transform: "Authorization Gatekeeper",
        to: "Signed Execution Lease (TTL: 60s)",
        toType: "SIMULATED",
        destination: "Layer 11 — Planning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Lease Signed Simulation",
        description: "auth_jwt_•••• envelope verified (PLANNED / MOCK)",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "JWT Signature Simulation",
        durationMs: 5.0,
        percentage: 55.6,
      },
      { operation: "TTL & Context Binding", durationMs: 4.0, percentage: 44.4 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.2,
      heapDeltaKb: 1.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 8.5,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.599",
        level: "SUCCESS",
        event: "authorization.approved",
        metadata: "Simulated lease issued (60s TTL [PLANNED / MOCK])",
      },
    ],
    rawJson: {
      layerId: 10,
      layerKey: "authorize",
      status: "success",
      lease: "APPROVED (PLANNED / MOCK)",
    },
  },
  {
    id: 11,
    name: "Planning",
    layerKey: "plan",
    responsibility:
      "Construct deterministic multi-step execution graph (DAG) and rollback handlers (PLAN != PERMISSION)",
    durationMs: 6,
    status: "success",
    health: "healthy",
    healthReason:
      "Generated single-action read-only DAG with no compensation needed (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.346",
    completedAt: "10:32:12.352",
    spanId: "spn_pln_00129",
    parentSpanId: "spn_auth_00129",
    previousLayer: "Layer 10 — Authorization",
    nextLayer: "Layer 12 — Durable Execution",
    inputContract: "SignedExecutionLease",
    outputContract: "ExecutablePlanGraph",
    owns: [
      "DAG topology ordering",
      "Timeout resolution",
      "Rollback action definition",
    ],
    doesNotOwn: ["Direct tool network calls", "Granting execution permissions"],
    internalFlow: [
      { step: "DAG Node Construction", durationMs: 2.0 },
      { step: "Rollback Handler Binding", durationMs: 2.0 },
      { step: "Graph Validation", durationMs: 2.0 },
    ],
    inputData: { action: "gmail.list_messages", leaseId: "lease_00129" },
    outputData: {
      totalSteps: 1,
      stepOrder: ["gmail.list_messages"],
      compensationHandler: "NONE (READ_ONLY)",
    },
    contractDiff: [
      {
        field: "planGraph",
        type: "ADDED",
        outputValue: "1-step execution DAG",
        note: "Validated step topology",
      },
    ],
    expectedVsActual: {
      expected:
        "ExecutablePlanGraph with ordered steps and rollback specifications",
      actual: "ExecutablePlanGraph (1 step DAG, 0 rollback dependencies)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Signed Execution Lease",
        fromType: "SIMULATED",
        transform: "DAG Planner Engine",
        to: "ExecutablePlanGraph (Node 1: gmail.list_messages)",
        toType: "DERIVED",
        destination: "Layer 12 — Durable Execution",
      },
    ],
    evidenceChecks: [
      {
        checkName: "DAG Acyclic Check",
        description: "Zero circular dependencies",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "DAG Node Construction", durationMs: 2.0, percentage: 33.3 },
      { operation: "Rollback Binding", durationMs: 2.0, percentage: 33.3 },
      { operation: "Graph Validation", durationMs: 2.0, percentage: 33.3 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.6,
      heapDeltaKb: 1.2,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 4.8,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.605",
        level: "INFO",
        event: "plan.constructed",
        metadata: "1-step execution graph ready",
      },
    ],
    rawJson: { layerId: 11, layerKey: "plan", status: "success", steps: 1 },
  },
  {
    id: 12,
    name: "Durable Execution",
    layerKey: "durable_execution",
    responsibility:
      "Persist execution claim & idempotency key in state machine to survive crashes and avoid duplicate actions",
    durationMs: 12,
    status: "success",
    health: "healthy",
    healthReason:
      "Idempotency key locked in durable state. Safe against duplicate retries (PLANNED / MOCK).",
    provenance: "PLANNED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.352",
    completedAt: "10:32:12.364",
    spanId: "spn_dur_00129",
    parentSpanId: "spn_pln_00129",
    previousLayer: "Layer 11 — Planning",
    nextLayer: "Layer 13 — Tool / Adapter Action",
    inputContract: "ExecutablePlanGraph",
    outputContract: "DurableExecutionClaim [PLANNED ARCHITECTURE / MOCK]",
    owns: [
      "Idempotency key enforcement",
      "Crash recovery claim storage",
      "Stale write protection",
    ],
    doesNotOwn: ["HTTP network communication"],
    internalFlow: [
      { step: "Generate Idempotency Hash", durationMs: 3.0 },
      { step: "Acquire DB Lease Lock (SIMULATED)", durationMs: 6.0 },
      { step: "Confirm Execution Claim", durationMs: 3.0 },
    ],
    inputData: {
      idempotencyKey: "idem_gmail_summarize_20260527",
      workerId: "worker_node_01",
    },
    outputData: {
      claimStatus: "CLAIMED (SIMULATED)",
      lockTtlSeconds: 60,
      retrySafe: true,
    },
    contractDiff: [
      {
        field: "durableClaimId",
        type: "ADDED",
        outputValue: "claim_00129_wk1",
        note: "Persisted in PostgreSQL state machine",
      },
      {
        field: "idempotencyLocked",
        type: "ADDED",
        outputValue: "true",
        note: "Duplicate requests will replay result",
      },
    ],
    expectedVsActual: {
      expected: "DurableExecutionClaim with valid DB lock and idempotency key",
      actual: "DurableExecutionClaim (Locked, TTL: 60s [PLANNED / MOCK])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "ExecutablePlanGraph",
        fromType: "DERIVED",
        transform: "PostgreSQL Lease Claim Engine",
        to: "DurableExecutionClaim (claim_00129_wk1)",
        toType: "SIMULATED",
        destination: "Layer 13 — Tool / Adapter Action",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Idempotency Key Locked",
        description: "Protected against duplicate network executions",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Hash Generation", durationMs: 3.0, percentage: 25.0 },
      { operation: "DB Lock Acquisition", durationMs: 6.0, percentage: 50.0 },
      { operation: "Claim Confirmation", durationMs: 3.0, percentage: 25.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.2,
      heapDeltaKb: 1.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 7.2,
    },
    layerLogs: [
      {
        timestamp: "10:32:12.618",
        level: "SUCCESS",
        event: "durable.claimed",
        metadata: "Lease lock confirmed in state machine",
      },
    ],
    rawJson: {
      layerId: 12,
      layerKey: "durable_execution",
      status: "success",
      claimId: "claim_00129_wk1",
    },
  },
  {
    id: 13,
    name: "Tool / Adapter Action",
    layerKey: "act",
    responsibility:
      "Dispatch controlled external HTTP GET request to Gmail REST API v1 (Unified Tool Gateway)",
    durationMs: 580,
    status: "success",
    health: "slow",
    healthReason:
      "HTTP GET simulated 200 OK with 5 messages in 580ms (SIMULATED). Network roundtrip bottleneck.",
    provenance: "SIMULATED",
    isCriticalPath: true,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 3",
    retryCount: 0,
    startedAt: "10:32:12.364",
    completedAt: "10:32:12.944",
    spanId: "spn_act_00129",
    parentSpanId: "spn_dur_00129",
    previousLayer: "Layer 12 — Durable Execution",
    nextLayer: "Layer 14 — Observation",
    inputContract: "DurableExecutionClaim [PLANNED ARCHITECTURE / MOCK]",
    outputContract: "RawToolHttpResponse [SIMULATED]",
    owns: [
      "HTTP protocol dispatch",
      "Network retry handling",
      "Status code verification",
    ],
    doesNotOwn: [
      "Post-check business verification",
      "Security policy decisions",
    ],
    internalFlow: [
      { step: "Construct HTTP request", durationMs: 15.0 },
      {
        step: "Network roundtrip to api.gmail.com (SIMULATED)",
        durationMs: 550.0,
      },
      { step: "Parse 200 OK payload", durationMs: 15.0 },
    ],
    inputData: GMAIL_SIMULATION.request,
    outputData: GMAIL_SIMULATION.response,
    contractDiff: [
      {
        field: "httpStatus",
        type: "ADDED",
        outputValue: "200 OK",
        note: "API responded successfully",
      },
      {
        field: "rawMessagesPayload",
        type: "ADDED",
        outputValue: "5 Gmail message items (18.4 KB)",
        note: "Extracted from response body",
      },
    ],
    expectedVsActual: {
      expected: "HTTP 200 response with message array matching query filters",
      actual: "HTTP 200 OK (5 messages returned, latency: 580ms [SIMULATED])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Durable Claim + Query parameters",
        fromType: "DERIVED",
        transform: "Gmail REST API GET Dispatch",
        to: "5 Raw Message Items (HTTP 200)",
        toType: "SIMULATED",
        destination: "Layer 14 — Observation",
      },
    ],
    evidenceChecks: [
      {
        checkName: "HTTP 200 OK Simulation",
        description: "Gmail API responded successfully (SIMULATED)",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Request Serialization", durationMs: 15.0, percentage: 2.6 },
      { operation: "Network Roundtrip", durationMs: 550.0, percentage: 94.8 },
      { operation: "Response Ingestion", durationMs: 15.0, percentage: 2.6 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 11.2,
      heapDeltaKb: 18.4,
      eventLoopLagMs: 0.04,
      memoryAllocatedKb: 64.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.169",
        level: "INFO",
        event: "gmail.started",
        metadata: "GET messages dispatched (SIMULATED)",
      },
      {
        timestamp: "10:32:13.521",
        level: "SUCCESS",
        event: "gmail.success",
        metadata: "200 OK (5 items [SIMULATED])",
      },
    ],
    rawJson: {
      layerId: 13,
      layerKey: "act",
      status: "success",
      httpStatus: 200,
      items: 5,
    },
  },
  {
    id: 14,
    name: "Observation",
    layerKey: "observe",
    responsibility:
      "Record immutable external reality & compute SHA256 integrity hash (TOOL RESPONSE != OBSERVED REALITY)",
    durationMs: 82,
    status: "success",
    health: "healthy",
    healthReason:
      "Observation recorded with SHA256 integrity hash in 82ms (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:12.944",
    completedAt: "10:32:13.026",
    spanId: "spn_obs_00129",
    parentSpanId: "spn_act_00129",
    previousLayer: "Layer 13 — Tool / Adapter Action",
    nextLayer: "Layer 15 — Verification",
    inputContract: "RawToolHttpResponse",
    outputContract: "ImmutableObservationRecord",
    owns: [
      "Payload structuring",
      "Integrity hashing",
      "Observation persistence",
    ],
    doesNotOwn: ["Business rule assertion checks"],
    internalFlow: [
      { step: "Parse RFC 5322 headers", durationMs: 24.0 },
      { step: "Extract sender identities", durationMs: 28.0 },
      { step: "Generate summary digest", durationMs: 30.0 },
    ],
    inputData: {
      rawBytes: GMAIL_SIMULATION.response.payloadBytes,
      itemsCount: GMAIL_SIMULATION.response.itemsReceived,
    },
    outputData: GMAIL_SIMULATION.observation,
    contractDiff: [
      {
        field: "observedState",
        type: "ADDED",
        outputValue: "5 message IDs confirmed present in mailbox",
        note: "Observed external reality",
      },
      {
        field: "topSenders",
        type: "ADDED",
        outputValue: "HR, John Doe, Finance",
        note: "Extracted from headers",
      },
    ],
    expectedVsActual: {
      expected:
        "ImmutableObservationRecord with extracted entities and payload hash",
      actual: "ImmutableObservationRecord (5 items, SHA256 verified)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "5 Raw Message Items",
        fromType: "SIMULATED",
        transform: "Header Parser & Integrity Hasher",
        to: "Immutable Observation (3 Senders, 5 Items)",
        toType: "DERIVED",
        destination: "Layer 15 — Verification",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Observation Immutability",
        description: "Hash verified (SIMULATED)",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Header Parsing", durationMs: 24.0, percentage: 29.3 },
      { operation: "Sender Extraction", durationMs: 28.0, percentage: 34.1 },
      { operation: "Digest Generation", durationMs: 30.0, percentage: 36.6 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 4.8,
      heapDeltaKb: 6.5,
      eventLoopLagMs: 0.02,
      memoryAllocatedKb: 22.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.521",
        level: "SUCCESS",
        event: "observation.received",
        metadata: "5 messages normalized",
      },
    ],
    rawJson: {
      layerId: 14,
      layerKey: "observe",
      status: "success",
      sendersCount: 3,
    },
  },
  {
    id: 15,
    name: "Verification",
    layerKey: "verify",
    responsibility:
      "Execute deterministic post-checks to independently verify business outcome (AI SUCCESS CLAIM != VERIFIED OUTCOME)",
    durationMs: 72,
    status: "success",
    health: "healthy",
    healthReason:
      "5/5 deterministic post-check assertions passed. Output verified (DERIVED).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:13.026",
    completedAt: "10:32:13.098",
    spanId: "spn_ver_00129",
    parentSpanId: "spn_obs_00129",
    previousLayer: "Layer 14 — Observation",
    nextLayer: "Layer 16 — Reward",
    inputContract: "ImmutableObservationRecord",
    outputContract: "VerificationResult",
    owns: ["Deterministic post-check invariants", "Final state sign-off"],
    doesNotOwn: ["AI generation", "Reward scoring"],
    internalFlow: [
      { step: "Assert message count === 5", durationMs: 20.0 },
      { step: "Assert scope === read_only", durationMs: 22.0 },
      { step: "Assert zero error codes", durationMs: 30.0 },
    ],
    inputData: {
      observedItems: GMAIL_SIMULATION.observation.observedItems,
      expectedItems: GMAIL_SIMULATION.response.itemsReceived,
    },
    outputData: GMAIL_SIMULATION.verification,
    contractDiff: [
      {
        field: "verificationOutcome",
        type: "ADDED",
        outputValue: "VERIFIED (5/5 assertions passed)",
        note: "Deterministic proof of correctness",
      },
      {
        field: "safetyInvariantCheck",
        type: "ADDED",
        outputValue: "AI success claim != Verified outcome",
        note: "Independently verified",
      },
    ],
    expectedVsActual: {
      expected: "5 unread emails from today with 100% assertion pass rate",
      actual: "5 verified emails, 5/5 assertions PASS (Confidence: 0.92)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Immutable Observation + Expected Goal",
        fromType: "DERIVED",
        transform: "Deterministic Assertion Engine",
        to: "Final Verified Outcome (VERIFIED)",
        toType: "DERIVED",
        destination: "Layer 16 — Reward",
      },
    ],
    evidenceChecks: [
      {
        checkName: "AI Claim != Outcome",
        description: "Verified independently via assertions",
        status: "PASS",
      },
      {
        checkName: "Message Count Invariant",
        description: "5 messages observed == 5 expected",
        status: "PASS",
      },
      {
        checkName: "Scope Invariant",
        description: "Execution remained read-only",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "Message Count Assertion",
        durationMs: 20.0,
        percentage: 27.8,
      },
      {
        operation: "Scope Invariant Assertion",
        durationMs: 22.0,
        percentage: 30.6,
      },
      {
        operation: "Error Code Invariant Check",
        durationMs: 30.0,
        percentage: 41.6,
      },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 2.8,
      heapDeltaKb: 3.9,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 16.0,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.593",
        level: "SUCCESS",
        event: "verification.passed",
        metadata: "Outcome: VERIFIED (DERIVED)",
      },
    ],
    rawJson: {
      layerId: 15,
      layerKey: "verify",
      status: "success",
      outcome: "VERIFIED",
    },
  },
  {
    id: 16,
    name: "Reward",
    layerKey: "reward",
    responsibility:
      "Convert VERIFIED outcome into a structured reinforcement reward signal (REWARD != PERMISSION)",
    durationMs: 16,
    status: "success",
    health: "healthy",
    healthReason:
      "Reward scored 0.90 based on task success (0.94) minus latency penalty (0.03) and cost penalty (0.01) [SIMULATED].",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:13.098",
    completedAt: "10:32:13.114",
    spanId: "spn_rew_00129",
    parentSpanId: "spn_ver_00129",
    previousLayer: "Layer 15 — Verification",
    nextLayer: "Layer 17 — Learning",
    inputContract: "VerificationResult (VERIFIED)",
    outputContract: "RewardSignal (AutoDo Schema v1.0 [SIMULATED])",
    owns: [
      "Deterministic reward scoring",
      "Calibration metrics calculation",
      "Penalty computation",
    ],
    doesNotOwn: [
      "Granting execution permissions (REWARD != PERMISSION)",
      "Bypassing policy or safety rules",
    ],
    internalFlow: [
      { step: "Evaluate verification score", durationMs: 4.0 },
      { step: "Calculate latency & cost penalties", durationMs: 6.0 },
      { step: "Assemble RewardSignal payload", durationMs: 6.0 },
    ],
    inputData: {
      verificationStatus: "VERIFIED",
      taskSuccess: true,
      qualityScore: 0.94,
      latencyMs: 2054,
      costUsd: 0.0021,
    },
    outputData: {
      verificationStatus: "VERIFIED",
      taskSuccess: true,
      qualityScore: 0.94,
      latencyPenalty: 0.03,
      costPenalty: 0.01,
      finalReward: 0.9,
      confidenceCalibration: 0.96,
      rewardReason:
        "Goal satisfied with verified 5 unread items within latency SLA",
      rewardVersion: "v1.0",
    },
    contractDiff: [
      {
        field: "finalReward",
        type: "ADDED",
        outputValue: "0.90 (Quality 0.94 - Latency 0.03 - Cost 0.01)",
        note: "Deterministic outcome score",
      },
      {
        field: "permissionState",
        type: "PRESERVED",
        outputValue: "REWARD != PERMISSION (No security change)",
        note: "Safety boundary enforced",
      },
    ],
    expectedVsActual: {
      expected: "RewardSignal with finalReward in range [0.0, 1.0]",
      actual: "RewardSignal (finalReward: 0.90, taskSuccess: true [SIMULATED])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Verified Outcome (VERIFIED)",
        fromType: "DERIVED",
        transform: "Outcome Scoring Matrix",
        to: "RewardSignal (finalReward: 0.90)",
        toType: "DERIVED",
        destination: "Layer 17 — Learning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Reward != Permission",
        description: "Reward score cannot bypass policy or authorization",
        status: "PASS",
      },
      {
        checkName: "Reward Range Bounds",
        description: "0.90 is within [0.0, 1.0] interval",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "Verification Score Evaluation",
        durationMs: 4.0,
        percentage: 25.0,
      },
      { operation: "Penalty Computation", durationMs: 6.0, percentage: 37.5 },
      { operation: "Signal Serialization", durationMs: 6.0, percentage: 37.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.1,
      heapDeltaKb: 1.5,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.2,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.610",
        level: "SUCCESS",
        event: "reward.computed",
        metadata: "Score: 0.90 (Quality: 0.94, Penalty: 0.04 [SIMULATED])",
      },
    ],
    rawJson: {
      layerId: 16,
      layerKey: "reward",
      status: "success",
      finalReward: 0.9,
      version: "v1.0",
    },
  },
  {
    id: 17,
    name: "Learning",
    layerKey: "learn",
    responsibility:
      "Generate ranking adjustments, tool reliability signals, and pattern feedback (LEARNING != AUTHORITY)",
    durationMs: 22,
    status: "success",
    health: "healthy",
    healthReason:
      "Generated +0.04 candidate weight adjustment for gmail.list_messages (SIMULATED).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:13.114",
    completedAt: "10:32:13.136",
    spanId: "spn_lrn_00129",
    parentSpanId: "spn_rew_00129",
    previousLayer: "Layer 16 — Reward",
    nextLayer: "Layer 18 — Verified Memory",
    inputContract: "RewardSignal + VerificationResult + RunContext",
    outputContract: "LearningUpdate (AutoDo Schema v1.0 [SIMULATED])",
    owns: [
      "Pattern extraction",
      "Candidate weight adjustment computation",
      "Provider quality telemetry",
    ],
    doesNotOwn: [
      "Modifying policy rules",
      "Granting permissions",
      "Changing authorization (LEARNING != AUTHORITY)",
    ],
    internalFlow: [
      { step: "Extract successful workflow pattern", durationMs: 8.0 },
      { step: "Calculate candidate ranking adjustment", durationMs: 7.0 },
      { step: "Package LearningUpdate bundle", durationMs: 7.0 },
    ],
    inputData: {
      rewardSignal: { finalReward: 0.9 },
      verificationResult: { status: "VERIFIED" },
      action: "gmail.list_messages",
    },
    outputData: {
      successfulPattern: "gmail.list_messages for read-only email summary",
      candidateAdjustment: {
        "gmail.list_messages": 0.04,
      },
      providerSignal: {
        provider: "gemini-2.5-pro",
        quality: 0.94,
      },
      toolSignal: {
        tool: "gmail.list_messages",
        success: true,
      },
      futureRecommendation:
        "Retain read-only query pattern for inbox digest goals",
    },
    contractDiff: [
      {
        field: "candidateAdjustment.gmail.list_messages",
        type: "ADDED",
        outputValue: "+0.04 (Weight bonus)",
        note: "Improves future ranking",
      },
      {
        field: "authorityState",
        type: "PRESERVED",
        outputValue: "LEARNING != AUTHORITY (Policy unchanged)",
        note: "Safety boundary enforced",
      },
    ],
    expectedVsActual: {
      expected:
        "LearningUpdate with pattern and non-authoritative candidate adjustment",
      actual:
        "LearningUpdate (1 successful pattern, +0.04 weight adjustment [SIMULATED])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "RewardSignal (0.90) + Verified State",
        fromType: "DERIVED",
        transform: "Reinforcement Weight Calculator",
        to: "LearningUpdate (Pattern: gmail.list_messages)",
        toType: "DERIVED",
        destination: "Layer 18 — Verified Memory",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Learning != Authority",
        description: "Learning signals cannot modify RBAC policies",
        status: "PASS",
      },
      {
        checkName: "Adjustment Bounds",
        description: "+0.04 delta is within ±0.10 step limit",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Pattern Extraction", durationMs: 8.0, percentage: 36.4 },
      {
        operation: "Candidate Weight Adjustment",
        durationMs: 7.0,
        percentage: 31.8,
      },
      {
        operation: "Learning Bundle Packaging",
        durationMs: 7.0,
        percentage: 31.8,
      },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.4,
      heapDeltaKb: 2.0,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 9.4,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.632",
        level: "SUCCESS",
        event: "learning.recorded",
        metadata: "Pattern: gmail.list_messages (+0.04 adjustment [SIMULATED])",
      },
    ],
    rawJson: {
      layerId: 17,
      layerKey: "learn",
      status: "success",
      adjustment: 0.04,
    },
  },
  {
    id: 18,
    name: "Verified Memory",
    layerKey: "verified_memory",
    responsibility:
      "Persist verified knowledge & reusable workflow patterns (VERIFIED MEMORY != AUTHORIZATION)",
    durationMs: 38,
    status: "success",
    health: "healthy",
    healthReason:
      "Stored 1 verified workflow memory fragment (#MEM-00129) and rejected 1 transient latency item (SIMULATED).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:32:13.136",
    completedAt: "10:32:13.174",
    spanId: "spn_vmem_00129",
    parentSpanId: "spn_lrn_00129",
    previousLayer: "Layer 17 — Learning",
    nextLayer: "FINAL RESULT (Terminal Outcome)",
    inputContract: "LearningUpdate + VerificationResult + CandidateMemory",
    outputContract:
      "VerifiedMemoryWriteResult (AutoDo Schema v1.0 [SIMULATED])",
    owns: [
      "Memory candidate verification check",
      "Deduplication & retention filter",
      "Verified vector embedding storage in pgvector [PLANNED]",
    ],
    doesNotOwn: [
      "Authorizing future executions (VERIFIED MEMORY != AUTHORIZATION)",
      "Bypassing policy gates",
    ],
    internalFlow: [
      {
        step: "Candidate Memory Quality & Verification Filter",
        durationMs: 10.0,
      },
      { step: "Deduplication & Retention Check", durationMs: 12.0 },
      {
        step: "Store Verified Memory in pgvector (SIMULATED)",
        durationMs: 16.0,
      },
    ],
    inputData: {
      candidatesCount: 2,
      candidate1: {
        type: "workflow_pattern",
        content: "gmail.list_messages for read-only digest",
      },
      candidate2: {
        type: "transient_latency",
        content: "Gmail API 580ms latency spike",
      },
    },
    outputData: {
      memoryId: "mem_verified_00129",
      type: "workflow_pattern",
      content:
        "gmail.list_messages successfully handled read-only unread-important summarization",
      sourceRunId: "run_2026_05_27_00129",
      verified: true,
      confidence: 0.94,
      writeStatus: "stored",
      storedCount: 1,
      rejectedCount: 1,
      rejectionReason:
        "Transient network latency is not useful as durable long-term memory",
    },
    contractDiff: [
      {
        field: "memoryId",
        type: "ADDED",
        outputValue: "mem_verified_00129",
        note: "Persisted to long-term memory",
      },
      {
        field: "storedDecision",
        type: "ADDED",
        outputValue: "1 stored, 1 rejected",
        note: "Retention filter executed",
      },
      {
        field: "permissionState",
        type: "PRESERVED",
        outputValue: "MEMORY != PERMISSION (Future runs still require Policy)",
        note: "Safety boundary enforced",
      },
    ],
    expectedVsActual: {
      expected:
        "VerifiedMemoryWriteResult with stored item and deduplication confirmation",
      actual:
        "VerifiedMemoryWriteResult (mem_verified_00129 stored, 1 rejected [SIMULATED])",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "LearningUpdate + Verification Proof",
        fromType: "DERIVED",
        transform: "Retention & Deduplication Filter",
        to: "Durable Verified Memory (#MEM-00129)",
        toType: "SIMULATED",
        destination: "Long-Term Knowledge Base",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Memory != Authorization",
        description: "Stored memories do NOT grant autonomous execution rights",
        status: "PASS",
      },
      {
        checkName: "Verification Gate Passed",
        description: "Only verified outcomes can enter long-term storage",
        status: "PASS",
      },
      {
        checkName: "Transient Data Filtered",
        description: "Non-durable telemetry rejected cleanly",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "Quality & Verification Filter",
        durationMs: 10.0,
        percentage: 26.3,
      },
      {
        operation: "Deduplication & Retention Check",
        durationMs: 12.0,
        percentage: 31.6,
      },
      { operation: "pgvector Index Store", durationMs: 16.0, percentage: 42.1 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 2.2,
      heapDeltaKb: 3.4,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 14.8,
    },
    layerLogs: [
      {
        timestamp: "10:32:13.670",
        level: "SUCCESS",
        event: "memory.stored",
        metadata: "ID: mem_verified_00129 (Type: workflow_pattern [SIMULATED])",
      },
      {
        timestamp: "10:32:13.671",
        level: "INFO",
        event: "memory.rejected",
        metadata: "Transient latency candidate rejected (Non-durable)",
      },
    ],
    rawJson: {
      layerId: 18,
      layerKey: "verified_memory",
      status: "success",
      memoryId: "mem_verified_00129",
      writeStatus: "stored",
    },
  },
];

export function buildSimulatedRunSnapshot(
  completedThrough: number,
): SimulatedRunSnapshot {
  const boundedStep = Math.max(
    1,
    Math.min(PIPELINE_STEPS.length, Math.trunc(completedThrough)),
  );
  const activeLayer = PIPELINE_STEPS[boundedStep - 1];

  return {
    status: boundedStep === PIPELINE_STEPS.length ? "completed" : "running",
    completedThrough: boundedStep,
    completedLayerIds: PIPELINE_STEPS.slice(0, boundedStep).map(
      (layer) => layer.id,
    ),
    activeLayer,
    currentInput: activeLayer.inputData,
    currentOutput: activeLayer.outputData,
    nextDestination: activeLayer.nextLayer,
    finalResultAvailable: boundedStep === PIPELINE_STEPS.length,
  };
}
