import type { ScheduleItem, TriggerSource } from "../contracts";

export const TRIGGER_SOURCES: readonly TriggerSource[] = [
  {
    id: "trg_chat",
    source: "Chat",
    condition: "User interactive message in web client",
    payloadPreview: "User prompt text",
    lastFired: "May 27, 2026 10:32 AM",
    enabled: true,
    runsCreated: 42,
  },
  {
    id: "trg_manual",
    source: "Manual Run",
    condition: "Trigger Run button clicked by developer",
    payloadPreview: '{"goal": "Summarize unread..."}',
    lastFired: "May 27, 2026 10:32 AM",
    enabled: true,
    runsCreated: 18,
  },
  {
    id: "trg_morning_cron",
    source: "Schedule",
    condition: "cron(0 8 * * *) Daily at 08:00 AM",
    payloadPreview: '{"briefing": "morning_digest"}',
    lastFired: "May 27, 2026 08:00 AM",
    nextFire: "May 28, 2026 08:00 AM",
    enabled: true,
    runsCreated: 120,
  },
  {
    id: "trg_gmail_push",
    source: "Gmail Event",
    condition: "Pub/Sub message on new urgent email",
    payloadPreview: '{"historyId": "98129"}',
    lastFired: "May 27, 2026 09:14 AM",
    enabled: true,
    runsCreated: 5,
  },
  {
    id: "trg_webhook",
    source: "Webhook",
    condition: "POST /api/v1/webhooks/ingress",
    payloadPreview: '{"event": "task_trigger"}',
    lastFired: "May 26, 2026 04:00 PM",
    enabled: true,
    runsCreated: 14,
  },
];

export const SCHEDULES: readonly ScheduleItem[] = [
  {
    id: "sch_morning",
    goal: "Morning Executive Briefing",
    triggerType: "Recurring Task",
    timezone: "Asia/Manila",
    recurrence: "Daily at 08:00 AM",
    nextRun: "May 28, 2026 08:00 AM",
    lastRun: "May 27, 2026 08:00 AM",
    status: "ACTIVE",
    failureCount: 0,
    associatedRunId: "run_2026_05_27_00045",
  },
  {
    id: "sch_followup",
    goal: "Follow up with John Doe if no reply",
    triggerType: "Follow-Up",
    timezone: "Asia/Manila",
    recurrence: "In 3 days (May 30)",
    nextRun: "May 30, 2026 10:00 AM",
    lastRun: "N/A",
    status: "PENDING",
    failureCount: 0,
    associatedRunId: "run_2026_05_27_00129",
  },
  {
    id: "sch_invoice_watch",
    goal: "Conditional watch for invoice receipt",
    triggerType: "Conditional Watch",
    timezone: "Asia/Manila",
    recurrence: "Hourly check",
    nextRun: "May 27, 2026 11:00 AM",
    lastRun: "May 27, 2026 10:00 AM",
    status: "ACTIVE",
    failureCount: 0,
    associatedRunId: "run_2026_05_27_00110",
  },
];
