import type { CapabilityItem, ToolRegistryItem } from "../contracts";

export const TOOL_REGISTRY: readonly ToolRegistryItem[] = [
  {
    id: "gmail.list_messages",
    provider: "Gmail",
    description: "List messages matching a read-only Gmail query.",
    inputSchema: "{ query: string; maxResults: number }",
    outputSchema: "{ messages: GmailMessageSummary[] }",
    risk: "LOW",
    requiredCapability: "cap_gmail_read",
    timeoutMs: 10_000,
    retryPolicy: "2 safe retries with exponential backoff",
    enabled: true,
    health: "SIMULATED HEALTHY",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "gmail.search_messages",
    provider: "Gmail",
    description: "Search Gmail using an authorized mailbox query.",
    inputSchema: "{ q: string; maxResults?: number }",
    outputSchema: "{ messages: GmailMessageSummary[] }",
    risk: "LOW",
    requiredCapability: "cap_gmail_search",
    timeoutMs: 10_000,
    retryPolicy: "2 safe retries with exponential backoff",
    enabled: true,
    health: "SIMULATED HEALTHY",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "gmail.get_message",
    provider: "Gmail",
    description: "Read one Gmail message by identifier.",
    inputSchema: "{ id: string; format?: string }",
    outputSchema: "{ message: GmailMessage }",
    risk: "LOW",
    requiredCapability: "cap_gmail_read",
    timeoutMs: 10_000,
    retryPolicy: "2 safe retries",
    enabled: true,
    health: "SIMULATED HEALTHY",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "gmail.draft_reply",
    provider: "Gmail",
    description: "Create a reply draft without sending it.",
    inputSchema: "{ threadId: string; body: string }",
    outputSchema: "{ draftId: string; messageId: string }",
    risk: "MEDIUM",
    requiredCapability: "cap_gmail_draft",
    timeoutMs: 10_000,
    retryPolicy: "Idempotency key required",
    enabled: false,
    health: "PLANNED",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "gmail.send_email",
    provider: "Gmail",
    description: "Send an email after policy and explicit approval checks.",
    inputSchema: "{ to: string[]; subject: string; body: string }",
    outputSchema: "{ messageId: string; threadId: string }",
    risk: "HIGH",
    requiredCapability: "cap_gmail_send",
    timeoutMs: 15_000,
    retryPolicy: "No blind retry; idempotency key required",
    enabled: false,
    health: "PLANNED",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "calendar.list_events",
    provider: "Google Calendar",
    description: "Read calendar events within an authorized time range.",
    inputSchema: "{ calendarId: string; start: string; end: string }",
    outputSchema: "{ events: CalendarEventSummary[] }",
    risk: "LOW",
    requiredCapability: "cap_cal_read",
    timeoutMs: 10_000,
    retryPolicy: "2 safe retries",
    enabled: false,
    health: "PLANNED",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "calendar.create_event",
    provider: "Google Calendar",
    description: "Create a calendar event after explicit approval.",
    inputSchema: "{ summary: string; start: string; attendees: string[] }",
    outputSchema: "{ eventId: string; htmlLink: string }",
    risk: "MEDIUM",
    requiredCapability: "cap_cal_create",
    timeoutMs: 15_000,
    retryPolicy: "No blind retry; idempotency key required",
    enabled: false,
    health: "PLANNED",
    implementationType: "NATIVE ADAPTER",
  },
  {
    id: "filesystem.read_file",
    provider: "Local Filesystem MCP",
    description: "Read an allowlisted local text file through an MCP server.",
    inputSchema: "{ path: string }",
    outputSchema: "{ content: string; metadata: object }",
    risk: "MEDIUM",
    requiredCapability: "cap_mcp_fs_read",
    timeoutMs: 5_000,
    retryPolicy: "1 safe retry",
    enabled: false,
    health: "PLANNED",
    implementationType: "MCP TOOL",
  },
  {
    id: "browser.navigate",
    provider: "Browser",
    description: "Navigate to an authorized URL before observation and verification.",
    inputSchema: "{ url: string }",
    outputSchema: "{ pageId: string; finalUrl: string; status: number }",
    risk: "LOW",
    requiredCapability: "cap_browser_nav",
    timeoutMs: 20_000,
    retryPolicy: "Recovery decision required",
    enabled: false,
    health: "PLANNED",
    implementationType: "INTERNAL TOOL",
  },
];

export const CAPABILITIES: readonly CapabilityItem[] = [
  {
    id: "cap_gmail_read",
    service: "Gmail",
    operation: "read_email",
    risk: "LOW",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "gmail.readonly",
    enabled: true,
  },
  {
    id: "cap_gmail_search",
    service: "Gmail",
    operation: "search_email",
    risk: "LOW",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "gmail.readonly",
    enabled: true,
  },
  {
    id: "cap_gmail_draft",
    service: "Gmail",
    operation: "draft_email",
    risk: "MEDIUM",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "gmail.modify",
    enabled: true,
  },
  {
    id: "cap_gmail_send",
    service: "Gmail",
    operation: "send_email",
    risk: "HIGH",
    defaultPolicy: "REQUIRE_APPROVAL",
    approvalMode: "REQUIRE_EXPLICIT_APPROVAL",
    scope: "gmail.send",
    enabled: true,
  },
  {
    id: "cap_gmail_delete",
    service: "Gmail",
    operation: "delete_email",
    risk: "CRITICAL",
    defaultPolicy: "DENY",
    approvalMode: "ALWAYS_DENY",
    scope: "gmail.modify",
    enabled: false,
  },
  {
    id: "cap_cal_read",
    service: "Google Calendar",
    operation: "read_events",
    risk: "LOW",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "calendar.readonly",
    enabled: true,
  },
  {
    id: "cap_cal_create",
    service: "Google Calendar",
    operation: "create_event",
    risk: "MEDIUM",
    defaultPolicy: "REQUIRE_APPROVAL",
    approvalMode: "REQUIRE_EXPLICIT_APPROVAL",
    scope: "calendar.events",
    enabled: true,
  },
  {
    id: "cap_mcp_fs_read",
    service: "MCP Filesystem",
    operation: "read_file",
    risk: "LOW",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "fs.read",
    enabled: true,
  },
  {
    id: "cap_mcp_fs_write",
    service: "MCP Filesystem",
    operation: "write_file",
    risk: "HIGH",
    defaultPolicy: "REQUIRE_APPROVAL",
    approvalMode: "REQUIRE_EXPLICIT_APPROVAL",
    scope: "fs.write",
    enabled: true,
  },
  {
    id: "cap_browser_nav",
    service: "Browser",
    operation: "navigate_and_read",
    risk: "LOW",
    defaultPolicy: "ALLOW",
    approvalMode: "AUTO_ALLOW",
    scope: "browser.read",
    enabled: true,
  },
];
