import type { AuditEvent } from "../contracts";

export const AUDIT_TRAIL: readonly AuditEvent[] = [
  {
    id: "aud_01",
    timestamp: "10:32:11.120",
    what: "User requested summary of unread emails",
    whoInitiated: "Developer (usr_dev_001)",
    why: "Interactive manual run trigger",
    permissionExisted: "Workspace Admin",
    whatChanged: "Run #run_2026_05_27_00129 created",
    evidenceSupported: "HTTP Ingress Body",
    outcomeAfterward: "Dispatched to Perception / Parsing",
  },
  {
    id: "aud_02",
    timestamp: "10:32:12.003",
    what: "AI proposed gmail.list_messages action",
    whoInitiated: "Gemini 2.5 Pro (Model Layer 5)",
    why: "Optimal tool for read-only inbox listing",
    permissionExisted: "None (AI Choice != Permission)",
    whatChanged: "Candidate proposal recorded",
    evidenceSupported: "Memory #MEM-012 retrieved",
    outcomeAfterward: "Sent to Grounding & Policy",
  },
  {
    id: "aud_03",
    timestamp: "10:32:12.579",
    what: "Policy Engine evaluated RULE_READONLY_AUTO_APPROVE",
    whoInitiated: "Deterministic Policy Engine (Layer 9)",
    why: "Action is read-only and non-destructive",
    permissionExisted: "RBAC Security Rules",
    whatChanged: "Policy Decision: ALLOW",
    evidenceSupported: "OAuth Scope gmail.readonly verified",
    outcomeAfterward: "Authorization Lease issued",
  },
  {
    id: "aud_04",
    timestamp: "10:32:12.599",
    what: "Authorization Gate issued cryptographic 60s lease",
    whoInitiated: "Authorization Gatekeeper (Layer 10)",
    why: "Policy ALLOW passed",
    permissionExisted: "Execution Lease Token",
    whatChanged: "Signed Execution Lease created",
    evidenceSupported: "Policy ALLOW envelope",
    outcomeAfterward: "Sent to Durable State Lock",
  },
  {
    id: "aud_05",
    timestamp: "10:32:13.521",
    what: "Gmail API returned HTTP 200 with 5 messages",
    whoInitiated: "Gmail Adapter Worker (Layer 13)",
    why: "Authorized plan execution",
    permissionExisted: "Signed Lease Token",
    whatChanged: "5 messages fetched",
    evidenceSupported: "HTTP 200 OK + SHA256",
    outcomeAfterward: "Recorded in Observation Layer",
  },
  {
    id: "aud_06",
    timestamp: "10:32:13.593",
    what: "Deterministic Post-Checks verified outcome",
    whoInitiated: "Verification Engine (Layer 15)",
    why: "AI claim != Verified outcome rule",
    permissionExisted: "System Assertion Suite",
    whatChanged: "Outcome set to VERIFIED (5/5 passed)",
    evidenceSupported: "5/5 Assertion proof",
    outcomeAfterward: "Reward Signal 0.90 generated",
  },
  {
    id: "aud_07",
    timestamp: "10:32:13.670",
    what: "Verified Memory stored workflow pattern",
    whoInitiated: "Verified Memory Engine (Layer 18)",
    why: "Passed quality & verification filter",
    permissionExisted: "Memory Retention Rule",
    whatChanged: "Stored #MEM-00129, rejected transient latency",
    evidenceSupported: "Verified proof",
    outcomeAfterward: "Run completed successfully",
  },
];

export const AUDIT_TRAIL_ASK_2: readonly AuditEvent[] = [
  {
    id: "aud_reply_01",
    timestamp: "10:40:00.100",
    what: "Incoming Gmail push event on thread_proposal_02",
    whoInitiated: "John Doe <john.doe@partner.org>",
    why: "Client requested 15-minute architecture sync",
    permissionExisted: "Gmail Webhook Token",
    whatChanged: "Run #run_20260527_reply_002 created",
    evidenceSupported: "Google Pub/Sub Webhook signature",
    outcomeAfterward: "Dispatched to Perception & Context",
  },
  {
    id: "aud_reply_02",
    timestamp: "10:40:00.950",
    what: "AI generated reply draft in Nelson's persona",
    whoInitiated: "Gemini 2.5 Pro (Model Layer 5)",
    why: "Calendar check verified Thursday 2:00 PM is free",
    permissionExisted: "None (AI Choice != Permission)",
    whatChanged: "Candidate action gmail.send_reply proposed",
    evidenceSupported: "Memory #MEM-019 (John Doe Trusted Partner)",
    outcomeAfterward: "Dispatched to Policy & Safety",
  },
  {
    id: "aud_reply_03",
    timestamp: "10:40:01.002",
    what: "Policy Engine evaluated TRUSTED_CONTACT_AUTO_REPLY_POLICY",
    whoInitiated: "Deterministic Policy Engine (Layer 9)",
    why: "Sender john.doe@partner.org is in Tier-1 allowlist",
    permissionExisted: "Allowlist Security Policy",
    whatChanged: "Policy Decision: ALLOW_WITH_AUDIT",
    evidenceSupported: "Verified contact record in #MEM-019",
    outcomeAfterward: "Authorization Lease issued",
  },
  {
    id: "aud_reply_04",
    timestamp: "10:40:01.015",
    what: "Authorization Gate issued cryptographic 60s write lease",
    whoInitiated: "Authorization Gatekeeper (Layer 10)",
    why: "Policy ALLOW passed",
    permissionExisted: "Execution Lease Token",
    whatChanged: "Signed Execution Lease lease_reply_20260527_002 bound to thread",
    evidenceSupported: "Policy ALLOW envelope",
    outcomeAfterward: "Dispatched to Durable Execution Claim",
  },
  {
    id: "aud_reply_05",
    timestamp: "10:40:01.810",
    what: "Gmail API sent RFC 2822 reply in thread_proposal_02",
    whoInitiated: "Gmail Adapter Worker (Layer 13)",
    why: "Authorized plan execution (Acting as Nelson)",
    permissionExisted: "Signed Lease Token",
    whatChanged: "Sent message msg_reply_9981_sent delivered",
    evidenceSupported: "HTTP 200 OK + Message ID returned",
    outcomeAfterward: "Recorded in Observation Layer",
  },
  {
    id: "aud_reply_06",
    timestamp: "10:40:01.830",
    what: "Deterministic Post-Checks verified in-thread delivery",
    whoInitiated: "Verification Engine (Layer 15)",
    why: "AI claim != Verified outcome rule",
    permissionExisted: "System Assertion Suite",
    whatChanged: "Outcome set to VERIFIED (6/6 passed)",
    evidenceSupported: "6/6 Assertion proof",
    outcomeAfterward: "Reward Signal 0.94 generated",
  },
  {
    id: "aud_reply_07",
    timestamp: "10:40:01.842",
    what: "Verified Memory stored partner sync record",
    whoInitiated: "Verified Memory Engine (Layer 18)",
    why: "Passed quality & verification filter",
    permissionExisted: "Memory Retention Rule",
    whatChanged: "Stored #MEM-00130 (Thu 2:00 PM sync confirmed)",
    evidenceSupported: "Verified proof",
    outcomeAfterward: "Run completed successfully",
  },
];

