import type { PipelineStep } from "../../contracts";

export const PIPELINE_STEPS_ASK_2: readonly PipelineStep[] = [
  {
    id: 1,
    name: "Input / Cue",
    layerKey: "cue",
    responsibility:
      "Ingress gateway boundary — receive incoming Gmail push webhook for client message",
    durationMs: 3,
    status: "success",
    health: "healthy",
    healthReason:
      "Gmail push event received with valid signature on thread_proposal_02 (3ms).",
    provenance: "OBSERVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.100",
    completedAt: "10:40:00.103",
    spanId: "spn_cue_reply_002",
    previousLayer: "Ingress Webhook (POST /api/webhooks/gmail [OBSERVED])",
    nextLayer: "Layer 2 — Perception / Parsing",
    inputContract: "GmailPushWebhookPayload (Origin: gmail.googleapis.com)",
    outputContract: "UnparsedCueEvent",
    owns: [
      "Webhook signature validation",
      "Trace ID correlation binding",
      "Message ID extraction",
    ],
    doesNotOwn: [
      "Semantic intent detection",
      "Policy evaluation",
      "Auto-reply generation",
    ],
    internalFlow: [
      { step: "Webhook HMAC verification", durationMs: 1.1 },
      { step: "Trace ID correlation binding", durationMs: 0.9 },
      { step: "Dispatch to Perception", durationMs: 1.0 },
    ],
    inputData: {
      httpMethod: "POST",
      path: "/api/webhooks/gmail",
      headers: {
        "x-goog-message-id": "msg_john_02",
        "x-trace-id": "trc_autodo_20260527_reply_02",
      },
      sourceSystem: "Gmail",
      origin: "gmail.googleapis.com",
      messageId: "msg_john_02",
      threadId: "thread_proposal_02",
      from: "John Doe <john.doe@partner.org>",
      subject: "Proposal follow-up for Q3 Architecture",
      snippet:
        "Following up on the Q3 architecture proposal draft we discussed yesterday afternoon...",
    },
    outputData: {
      cueId: "cue_gmail_reply_002",
      source: "gmail_push_notification",
      messageId: "msg_john_02",
      threadId: "thread_proposal_02",
      receivedAt: "2026-05-27T10:40:00.100Z",
    },
    contractDiff: [
      {
        field: "cueId",
        type: "ADDED",
        outputValue: "cue_gmail_reply_002",
        note: "Cue registered",
      },
      {
        field: "threadContext",
        type: "ADDED",
        outputValue: "thread_proposal_02",
        note: "Thread bound",
      },
    ],
    expectedVsActual: {
      expected: "UnparsedCueEvent with verified Gmail webhook signature",
      actual: "UnparsedCueEvent (signature verified, thread_proposal_02 bound)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Gmail Push Webhook: msg_john_02",
        fromType: "OBSERVED",
        transform: "HMAC Signature Verify",
        to: "UnparsedCueEvent (cue_gmail_reply_002)",
        toType: "DERIVED",
        destination: "Layer 2 — Perception / Parsing",
      },
    ],
    evidenceChecks: [
      {
        checkName: "HMAC Webhook Verified",
        description: "Google pub/sub signature verified",
        status: "PASS",
      },
      {
        checkName: "Valid Thread ID Bound",
        description: "thread_proposal_02 active",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      {
        operation: "Webhook Signature Validation",
        durationMs: 1.1,
        percentage: 36.7,
      },
      { operation: "Trace Context Binding", durationMs: 0.9, percentage: 30.0 },
      { operation: "Perception Dispatch", durationMs: 1.0, percentage: 33.3 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.7,
      heapDeltaKb: 1.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 5.2,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.100",
        level: "INFO",
        event: "cue.received",
        metadata: "Incoming message from John Doe on thread_proposal_02",
      },
    ],
    rawJson: { layerId: 1, cueId: "cue_gmail_reply_002", status: "SUCCESS" },
  },
  {
    id: 2,
    name: "Perception / Parsing",
    layerKey: "perceive",
    responsibility:
      "Parse incoming message intent into canonical AutoDo command (Auto-Reply Acting As Me)",
    durationMs: 8,
    status: "success",
    health: "healthy",
    healthReason: "Parsed intent: ACT_AS_USER_AUTO_REPLY (8ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.103",
    completedAt: "10:40:00.111",
    spanId: "spn_perceive_reply_002",
    previousLayer: "Layer 1 — Input / Cue",
    nextLayer: "Layer 3 — Context Build",
    inputContract: "UnparsedCueEvent",
    outputContract: "CanonicalCommand (Intent: ACT_AS_USER_AUTO_REPLY)",
    owns: [
      "Intent classification",
      "Entity extraction (Sender, Action item, Question)",
    ],
    doesNotOwn: ["Calendar lookup", "LLM draft generation", "Email sending"],
    internalFlow: [
      { step: "Message body tokenization", durationMs: 2.5 },
      { step: "Intent mapping: ACT_AS_USER_AUTO_REPLY", durationMs: 3.2 },
      { step: "Parameter normalization", durationMs: 2.3 },
    ],
    inputData: {
      cueId: "cue_gmail_reply_002",
      bodyText:
        "Hi Nelson, Following up on the Q3 architecture proposal draft we discussed yesterday afternoon. Let me know if you want to schedule a 15-minute call before we submit the final draft. Thanks, John",
      sender: "John Doe <john.doe@partner.org>",
    },
    outputData: {
      commandId: "cmd_reply_john_002",
      intent: "ACT_AS_USER_AUTO_REPLY",
      actionType: "PROPOSE_MEETING_TIME_AND_REPLY",
      targetSender: "John Doe",
      senderEmail: "john.doe@partner.org",
      meetingDurationRequestedMinutes: 15,
      threadId: "thread_proposal_02",
    },
    contractDiff: [
      {
        field: "intent",
        type: "ADDED",
        outputValue: "ACT_AS_USER_AUTO_REPLY",
        note: "Intent identified",
      },
      {
        field: "meetingDurationMinutes",
        type: "ADDED",
        outputValue: "15",
        note: "Extracted meeting request",
      },
    ],
    expectedVsActual: {
      expected: "CanonicalCommand with intent ACT_AS_USER_AUTO_REPLY",
      actual:
        "CanonicalCommand (Intent ACT_AS_USER_AUTO_REPLY, 15m duration detected)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "UnparsedCueEvent: cue_gmail_reply_002",
        fromType: "OBSERVED",
        transform: "Deterministic Intent Classifier",
        to: "CanonicalCommand (cmd_reply_john_002)",
        toType: "DERIVED",
        destination: "Layer 3 — Context Build",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Intent Recognized",
        description: "Intent matched ACT_AS_USER_AUTO_REPLY",
        status: "PASS",
      },
      {
        checkName: "Target Email Valid",
        description: "john.doe@partner.org valid RFC format",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Tokenization", durationMs: 2.5, percentage: 31.2 },
      { operation: "Intent Mapping", durationMs: 3.2, percentage: 40.0 },
      { operation: "Entity Extraction", durationMs: 2.3, percentage: 28.8 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.2,
      heapDeltaKb: 2.4,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 7.1,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.105",
        level: "INFO",
        event: "perceive.intent_mapped",
        metadata: "ACT_AS_USER_AUTO_REPLY detected for John Doe",
      },
    ],
    rawJson: {
      commandId: "cmd_reply_john_002",
      intent: "ACT_AS_USER_AUTO_REPLY",
    },
  },
  {
    id: 3,
    name: "Context Build",
    layerKey: "context",
    responsibility:
      "Assemble owner context, calendar availability, and communication style profile",
    durationMs: 12,
    status: "success",
    health: "healthy",
    healthReason:
      "Found calendar opening on Thu May 29 2:00 PM - 2:30 PM (12ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.111",
    completedAt: "10:40:00.123",
    spanId: "spn_context_reply_002",
    previousLayer: "Layer 2 — Perception / Parsing",
    nextLayer: "Layer 4 — Memory Retrieval",
    inputContract: "CanonicalCommand",
    outputContract:
      "ExecutionContextBundle (Owner Persona: Nelson + Free Calendar Slots)",
    owns: [
      "Calendar free-busy aggregation",
      "Owner persona metadata binding",
      "Token budget calculation",
    ],
    doesNotOwn: ["Vector search", "LLM generation", "Policy decisions"],
    internalFlow: [
      { step: "Calendar free-busy lookup", durationMs: 6.2 },
      { step: "Owner persona binding", durationMs: 3.1 },
      { step: "Context payload packaging", durationMs: 2.7 },
    ],
    inputData: {
      commandId: "cmd_reply_john_002",
      intent: "ACT_AS_USER_AUTO_REPLY",
      targetSender: "john.doe@partner.org",
      requestedDurationMinutes: 15,
    },
    outputData: {
      ownerName: "Nelson",
      ownerEmail: "dev@autodo.ai",
      timezone: "Asia/Manila",
      actingMode: "ACT_AS_USER (Nelson)",
      availableCalendarSlot: {
        startTime: "2026-05-29T14:00:00+08:00",
        endTime: "2026-05-29T14:30:00+08:00",
        formattedSlot: "Thursday, May 29, 2026 at 2:00 PM (Asia/Manila)",
      },
      tokenBudget: 512,
    },
    contractDiff: [
      {
        field: "availableCalendarSlot",
        type: "ADDED",
        outputValue: "Thu May 29 2:00 PM",
        note: "Found free slot",
      },
      {
        field: "actingMode",
        type: "ADDED",
        outputValue: "ACT_AS_USER",
        note: "Persona loaded",
      },
    ],
    expectedVsActual: {
      expected:
        "ExecutionContextBundle with valid calendar opening and Nelson profile",
      actual: "ExecutionContextBundle (Slot: Thu May 29 2:00 PM, Asia/Manila)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "CanonicalCommand: cmd_reply_john_002",
        fromType: "DERIVED",
        transform: "Calendar & Profile Aggregator",
        to: "ExecutionContextBundle",
        toType: "DERIVED",
        destination: "Layer 4 — Memory Retrieval",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Calendar Slot Conflict Free",
        description: "No overlapping events on May 29 2:00 PM",
        status: "PASS",
      },
      {
        checkName: "Timezone Normalized",
        description: "Asia/Manila (UTC+8)",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Calendar Lookup", durationMs: 6.2, percentage: 51.7 },
      { operation: "Persona Binding", durationMs: 3.1, percentage: 25.8 },
      { operation: "Context Packaging", durationMs: 2.7, percentage: 22.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.5,
      heapDeltaKb: 3.2,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 8.5,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.115",
        level: "INFO",
        event: "context.slot_found",
        metadata: "Next available meeting slot: Thu May 29 2:00 PM",
      },
    ],
    rawJson: {
      owner: "Nelson",
      timezone: "Asia/Manila",
      slot: "2026-05-29T14:00:00+08:00",
    },
  },
  {
    id: 4,
    name: "Memory Retrieval",
    layerKey: "memory_retrieval",
    responsibility:
      "Retrieve verified contact relationship and Nelson's communication tone guidelines",
    durationMs: 38,
    status: "success",
    health: "healthy",
    healthReason:
      "Retrieved #MEM-019 (John Doe trusted partner profile) with 0.95 similarity score (38ms).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.123",
    completedAt: "10:40:00.161",
    spanId: "spn_memory_reply_002",
    previousLayer: "Layer 3 — Context Build",
    nextLayer: "Layer 5 — AI Reasoning",
    inputContract:
      "ExecutionContextBundle (Query: John Doe partner relationship)",
    outputContract: "MemoryEnrichedContext (Tone & Relationship Profile)",
    owns: [
      "Vector similarity search",
      "Contact relationship lookup",
      "Communication guidelines injection",
    ],
    doesNotOwn: ["AI generation", "Policy authorization", "Email sending"],
    internalFlow: [
      { step: "Hybrid vector search (pgvector)", durationMs: 22.4 },
      { step: "Cross-encoder reranking", durationMs: 10.1 },
      { step: "Threshold filtering (> 0.80)", durationMs: 5.5 },
    ],
    inputData: {
      query: "John Doe communication guidelines and relationship history",
      contactId: "CONTACT_002",
      minSimilarity: 0.8,
    },
    outputData: {
      retrievedMemoryId: "MEM_019",
      contactName: "John Doe",
      relationship: "TRUSTED_EXTERNAL_PARTNER",
      preferredTone: "Professional, Warm, Direct",
      meetingPreference: "15-30 mins virtual sync",
      standardSignoff: "Best, Nelson",
      similarityScore: 0.95,
      selected: true,
    },
    contractDiff: [
      {
        field: "retrievedMemoryId",
        type: "ADDED",
        outputValue: "MEM_019",
        note: "Profile loaded",
      },
      {
        field: "preferredTone",
        type: "ADDED",
        outputValue: "Professional, Warm, Direct",
        note: "Tone bound",
      },
    ],
    expectedVsActual: {
      expected: "MemoryEnrichedContext with similarity >= 0.80",
      actual:
        "MemoryEnrichedContext (#MEM-019, similarity 0.95, Trusted Partner)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "Query: John Doe communication guidelines",
        fromType: "DERIVED",
        transform: "pgvector Hybrid Search",
        to: "MemoryEnrichedContext (#MEM-019)",
        toType: "DERIVED",
        destination: "Layer 5 — AI Reasoning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Relevance Score >= 0.80",
        description: "Similarity 0.95 passed threshold",
        status: "PASS",
      },
      {
        checkName: "Verified Trust Status",
        description: "John Doe marked TRUSTED_PARTNER",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Vector Search", durationMs: 22.4, percentage: 58.9 },
      { operation: "Reranking", durationMs: 10.1, percentage: 26.6 },
      { operation: "Threshold Gate", durationMs: 5.5, percentage: 14.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 4.1,
      heapDeltaKb: 8.2,
      eventLoopLagMs: 0.02,
      memoryAllocatedKb: 28.0,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.145",
        level: "INFO",
        event: "rag.memory_found",
        metadata: "Loaded #MEM-019 (John Doe Trusted Partner Profile)",
      },
    ],
    rawJson: { memoryId: "MEM_019", similarity: 0.95, tone: "Warm, Direct" },
  },
  {
    id: 5,
    name: "AI Reasoning",
    layerKey: "ai_reasoning",
    responsibility:
      "Reason over incoming message, available calendar slot, and compose auto-reply draft in Nelson's voice",
    durationMs: 742,
    status: "success",
    health: "healthy",
    healthReason:
      "Composed reply draft proposing Thu May 29 2:00 PM in Nelson's voice (742ms).",
    provenance: "SIMULATED",
    isCriticalPath: true,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.161",
    completedAt: "10:40:00.903",
    spanId: "spn_reason_reply_002",
    previousLayer: "Layer 4 — Memory Retrieval",
    nextLayer: "Layer 6 — Candidate Generation",
    inputContract: "ModelPromptPayload (Acting as Nelson)",
    outputContract:
      "StructuredReasoningPlan (Proposed Reply Draft & Calendar Hold)",
    owns: [
      "Message synthesis",
      "Reply text drafting in user's persona",
      "Tool proposal",
    ],
    doesNotOwn: [
      "Executing tool calls",
      "Bypassing policy",
      "Granting authorization",
    ],
    internalFlow: [
      { step: "Prompt token packaging", durationMs: 18.0 },
      { step: "Gemini 2.5 Pro JSON generation", durationMs: 698.0 },
      { step: "Structured schema validation", durationMs: 26.0 },
    ],
    inputData: {
      provider: "Google Gemini 2.5 Pro",
      persona: "Nelson (AI Assistant acting on behalf of Nelson)",
      incomingSender: "John Doe",
      proposedMeetingTime: "Thursday, May 29, 2026 at 2:00 PM (Asia/Manila)",
    },
    outputData: {
      reasoningSummary:
        "John Doe requested a 15-minute sync regarding the Q3 architecture proposal. Nelson has an open calendar slot on Thursday at 2:00 PM. Drafting an affirmative response proposing this time.",
      proposedSubject: "Re: Proposal follow-up for Q3 Architecture",
      proposedBody:
        "Hi John,\n\nThanks for following up. The Q3 architecture proposal draft looks very solid.\n\nI am free for a 15-minute sync on Thursday, May 29, 2026 at 2:00 PM (Asia/Manila time). I'll send over a calendar invite so we can align before final submission.\n\nBest,\nNelson",
      proposedActions: ["gmail.send_reply", "calendar.create_tentative_hold"],
      confidenceScore: 0.96,
    },
    contractDiff: [
      {
        field: "proposedBody",
        type: "ADDED",
        outputValue: "Hi John, Thanks for following up...",
        note: "Draft generated",
      },
      {
        field: "confidenceScore",
        type: "ADDED",
        outputValue: "0.96",
        note: "High confidence",
      },
    ],
    expectedVsActual: {
      expected:
        "StructuredReasoningPlan with composed reply and tool proposals",
      actual:
        "StructuredReasoningPlan (Draft composed in Nelson's voice, confidence 0.96)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "ModelPromptPayload (Nelson Persona + Calendar Slot)",
        fromType: "DERIVED",
        transform: "Gemini 2.5 Pro JSON Mode",
        to: "StructuredReasoningPlan",
        toType: "DERIVED",
        destination: "Layer 6 — Candidate Generation",
      },
    ],
    evidenceChecks: [
      {
        checkName: "JSON Schema Compliant",
        description: "Structured output matches schema",
        status: "PASS",
      },
      {
        checkName: "Persona Consistency Check",
        description: "Signoff matches Nelson's standard 'Best, Nelson'",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Prompt Packaging", durationMs: 18.0, percentage: 2.4 },
      {
        operation: "Model Generation (Gemini 2.5 Pro)",
        durationMs: 698.0,
        percentage: 94.1,
      },
      { operation: "Schema Validation", durationMs: 26.0, percentage: 3.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 12.4,
      heapDeltaKb: 42.0,
      eventLoopLagMs: 0.05,
      memoryAllocatedKb: 128.0,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.890",
        level: "INFO",
        event: "ai.draft_generated",
        metadata: "Auto-reply draft composed for John Doe (confidence: 0.96)",
      },
    ],
    rawJson: { model: "gemini-2.5-pro", draftLength: 268, confidence: 0.96 },
  },
  {
    id: 6,
    name: "Candidate Generation",
    layerKey: "candidate_generation",
    responsibility:
      "Generate explicit candidate actions for evaluation and ranking",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason: "Generated 3 candidate action strategies (4ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.903",
    completedAt: "10:40:00.907",
    spanId: "spn_cand_reply_002",
    previousLayer: "Layer 5 — AI Reasoning",
    nextLayer: "Layer 7 — Scoring & Ranking",
    inputContract: "StructuredReasoningPlan",
    outputContract: "CandidateActionSet (3 Action Proposals)",
    owns: ["Candidate action synthesis", "Tool parameter mapping"],
    doesNotOwn: ["Candidate scoring", "Policy enforcement", "Execution"],
    internalFlow: [
      { step: "Candidate action extraction", durationMs: 2.1 },
      { step: "Parameter structure validation", durationMs: 1.9 },
    ],
    inputData: {
      plan: "Auto-reply to John Doe proposing Thu 2PM sync",
    },
    outputData: {
      candidates: [
        {
          id: "cand_01",
          name: "Send Auto-Reply & Hold Calendar Slot",
          tool: "gmail.send_reply",
          parameters: {
            to: "john.doe@partner.org",
            threadId: "thread_proposal_02",
            time: "2026-05-29T14:00:00+08:00",
          },
          risk: "MUTATING_EXTERNAL_WRITE",
        },
        {
          id: "cand_02",
          name: "Create Draft Only (Human Must Click Send)",
          tool: "gmail.create_draft",
          parameters: {
            to: "john.doe@partner.org",
            threadId: "thread_proposal_02",
          },
          risk: "LOW_WRITE",
        },
        {
          id: "cand_03",
          name: "Notify Owner in Chat Only",
          tool: "notify.owner_chat",
          parameters: { message: "John Doe asked for a meeting" },
          risk: "READ_ONLY",
        },
      ],
    },
    contractDiff: [
      {
        field: "candidateCount",
        type: "ADDED",
        outputValue: "3",
        note: "3 options generated",
      },
    ],
    expectedVsActual: {
      expected: "CandidateActionSet with distinct execution strategies",
      actual:
        "CandidateActionSet (3 candidates: Auto-reply, Draft-only, Chat-notify)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "StructuredReasoningPlan",
        fromType: "DERIVED",
        transform: "Candidate Expander",
        to: "CandidateActionSet",
        toType: "DERIVED",
        destination: "Layer 7 — Scoring & Ranking",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Valid Candidates Count",
        description: "3 distinct action strategies generated",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Candidate Extraction", durationMs: 2.1, percentage: 52.5 },
      { operation: "Structure Validation", durationMs: 1.9, percentage: 47.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.9,
      heapDeltaKb: 2.1,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.0,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.905",
        level: "INFO",
        event: "candidates.generated",
        metadata: "Generated 3 action candidates",
      },
    ],
    rawJson: { count: 3, topCandidate: "cand_01" },
  },
  {
    id: 7,
    name: "Scoring & Ranking",
    layerKey: "scoring_ranking",
    responsibility:
      "Rank candidate actions deterministically based on user preferences and trust levels",
    durationMs: 3,
    status: "success",
    health: "healthy",
    healthReason:
      "Candidate 1 (Auto-Reply) scored 0.97 due to trusted partner status (3ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.907",
    completedAt: "10:40:00.910",
    spanId: "spn_score_reply_002",
    previousLayer: "Layer 6 — Candidate Generation",
    nextLayer: "Layer 8 — Grounding",
    inputContract: "CandidateActionSet",
    outputContract: "RankedCandidateProposal",
    owns: ["Deterministic multi-factor scoring", "Risk penalty calculation"],
    doesNotOwn: ["Granting authorization", "Bypassing policy"],
    internalFlow: [
      { step: "Utility scoring evaluation", durationMs: 1.5 },
      { step: "Risk weighting adjustment", durationMs: 1.5 },
    ],
    inputData: {
      candidatesEvaluated: ["cand_01", "cand_02", "cand_03"],
    },
    outputData: {
      rankedCandidates: [
        {
          id: "cand_01",
          score: 0.97,
          status: "SELECTED",
          reason:
            "Trusted partner allowlist enables autonomous meeting scheduling",
        },
        {
          id: "cand_02",
          score: 0.82,
          status: "ALTERNATIVE",
          reason: "Draft-only is safe but adds manual user latency",
        },
        {
          id: "cand_03",
          score: 0.65,
          status: "REJECTED",
          reason: "Fails to take action on simple scheduling request",
        },
      ],
      selectedCandidateId: "cand_01",
    },
    contractDiff: [
      {
        field: "selectedCandidateId",
        type: "ADDED",
        outputValue: "cand_01",
        note: "Ranked #1",
      },
      {
        field: "topScore",
        type: "ADDED",
        outputValue: "0.97",
        note: "Confidence score",
      },
    ],
    expectedVsActual: {
      expected:
        "RankedCandidateProposal with mathematically ranked candidate actions",
      actual: "RankedCandidateProposal (Top: cand_01 with 0.97 score)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "CandidateActionSet",
        fromType: "DERIVED",
        transform: "Deterministic Ranking Engine",
        to: "RankedCandidateProposal (cand_01)",
        toType: "DERIVED",
        destination: "Layer 8 — Grounding",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Ranking Separation Verified",
        description: "Top candidate exceeds #2 by 0.15 delta",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Utility Scoring", durationMs: 1.5, percentage: 50.0 },
      { operation: "Risk Adjustment", durationMs: 1.5, percentage: 50.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.8,
      heapDeltaKb: 1.9,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 5.4,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.909",
        level: "INFO",
        event: "scoring.completed",
        metadata: "cand_01 selected (score: 0.97)",
      },
    ],
    rawJson: { selected: "cand_01", score: 0.97 },
  },
  {
    id: 8,
    name: "Grounding",
    layerKey: "grounding",
    responsibility:
      "Ground proposed reply text and meeting time against real verified evidence",
    durationMs: 5,
    status: "success",
    health: "healthy",
    healthReason:
      "Grounded 100% of facts: Calendar opening verified, John Doe email verified (5ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.910",
    completedAt: "10:40:00.915",
    spanId: "spn_ground_reply_002",
    previousLayer: "Layer 7 — Scoring & Ranking",
    nextLayer: "Layer 9 — Policy / Safety",
    inputContract: "RankedCandidateProposal",
    outputContract: "GroundedProposalWithEvidence (100% Grounded Claims)",
    owns: [
      "Factual claim extraction",
      "Evidence verification against calendar and contact registry",
    ],
    doesNotOwn: ["Granting authorization", "Executing API calls"],
    internalFlow: [
      { step: "Claim extraction", durationMs: 2.2 },
      { step: "Calendar evidence verification", durationMs: 1.8 },
      { step: "Grounding envelope creation", durationMs: 1.0 },
    ],
    inputData: {
      candidateId: "cand_01",
      proposedTime: "Thursday, May 29, 2026 at 2:00 PM",
      recipient: "john.doe@partner.org",
    },
    outputData: {
      groundedClaims: [
        {
          claim: "Recipient is John Doe",
          evidenceRef: "CONTACT_002",
          status: "VERIFIED",
        },
        {
          claim: "Nelson is free May 29 2:00 PM - 2:30 PM",
          evidenceRef: "CALENDAR_SLOT_001",
          status: "VERIFIED",
        },
        {
          claim: "Thread context is Q3 Architecture Proposal",
          evidenceRef: "thread_proposal_02",
          status: "VERIFIED",
        },
      ],
      hallucinationRisk: 0.0,
      groundingScore: 1.0,
    },
    contractDiff: [
      {
        field: "groundingScore",
        type: "ADDED",
        outputValue: "1.0",
        note: "100% grounded",
      },
      {
        field: "hallucinationRisk",
        type: "ADDED",
        outputValue: "0.0",
        note: "Zero hallucination",
      },
    ],
    expectedVsActual: {
      expected: "GroundedProposalWithEvidence with zero ungrounded assertions",
      actual:
        "GroundedProposalWithEvidence (3/3 claims verified, groundingScore: 1.0)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "RankedCandidateProposal (cand_01)",
        fromType: "DERIVED",
        transform: "Factual Grounding Verifier",
        to: "GroundedProposalWithEvidence",
        toType: "DERIVED",
        destination: "Layer 9 — Policy / Safety",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Zero Hallucinated Claims",
        description: "All 3 claims backed by verified evidence",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Claim Extraction", durationMs: 2.2, percentage: 44.0 },
      { operation: "Evidence Verification", durationMs: 1.8, percentage: 36.0 },
      { operation: "Envelope Creation", durationMs: 1.0, percentage: 20.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.1,
      heapDeltaKb: 2.2,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.5,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.914",
        level: "INFO",
        event: "grounding.verified",
        metadata: "3/3 factual claims verified against calendar & contacts",
      },
    ],
    rawJson: { groundingScore: 1.0, claimsCount: 3 },
  },
  {
    id: 9,
    name: "Policy / Safety",
    layerKey: "policy_safety",
    responsibility:
      "Evaluate auto-reply action against safety policies and trusted contact allowlists",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason:
      "Policy ALLOW: Recipient is verified trusted contact with auto-reply permission (4ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.915",
    completedAt: "10:40:00.919",
    spanId: "spn_policy_reply_002",
    previousLayer: "Layer 8 — Grounding",
    nextLayer: "Layer 10 — Authorization",
    inputContract: "GroundedProposalWithEvidence",
    outputContract: "PolicyDecisionEnvelope (Decision: ALLOW_WITH_AUDIT)",
    owns: [
      "Policy rules evaluation outside the LLM",
      "Safety risk assessment",
      "Allowlist check",
    ],
    doesNotOwn: ["Cryptographic lease generation", "Tool execution"],
    internalFlow: [
      {
        step: "Rule evaluation: TRUSTED_CONTACT_AUTO_REPLY_POLICY",
        durationMs: 2.1,
      },
      { step: "Rate limit & time boundary check", durationMs: 1.9 },
    ],
    inputData: {
      actionProposed: "gmail.send_reply",
      recipient: "john.doe@partner.org",
      riskLevel: "MUTATING_EXTERNAL_WRITE",
    },
    outputData: {
      decision: "ALLOW_WITH_AUDIT",
      ruleEvaluated: "TRUSTED_CONTACT_AUTO_REPLY_POLICY",
      contactVerified: true,
      humanApprovalBypassedReason:
        "Explicitly pre-authorized delegation rule for trusted partner John Doe",
      auditLevel: "FULL_AUDIT_LEDGER",
    },
    contractDiff: [
      {
        field: "decision",
        type: "ADDED",
        outputValue: "ALLOW_WITH_AUDIT",
        note: "Policy approved",
      },
      {
        field: "ruleEvaluated",
        type: "ADDED",
        outputValue: "TRUSTED_CONTACT_AUTO_REPLY_POLICY",
        note: "Rule applied",
      },
    ],
    expectedVsActual: {
      expected: "PolicyDecisionEnvelope with explicit rule evaluation",
      actual:
        "PolicyDecisionEnvelope (Decision: ALLOW_WITH_AUDIT, Rule: TRUSTED_CONTACT_AUTO_REPLY)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "GroundedProposalWithEvidence",
        fromType: "DERIVED",
        transform: "Deterministic Policy Engine",
        to: "PolicyDecisionEnvelope",
        toType: "DERIVED",
        destination: "Layer 10 — Authorization",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Allowlist Policy Satisfied",
        description: "John Doe matches pre-authorized contact rule",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Rule Evaluation", durationMs: 2.1, percentage: 52.5 },
      { operation: "Rate Limit Check", durationMs: 1.9, percentage: 47.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.9,
      heapDeltaKb: 1.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 5.6,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.918",
        level: "INFO",
        event: "policy.allowed",
        metadata: "Policy ALLOW_WITH_AUDIT for John Doe auto-reply",
      },
    ],
    rawJson: {
      decision: "ALLOW_WITH_AUDIT",
      rule: "TRUSTED_CONTACT_AUTO_REPLY_POLICY",
    },
  },
  {
    id: 10,
    name: "Authorization",
    layerKey: "authorization",
    responsibility:
      "Issue time-bound cryptographic HMAC execution lease for gmail.send in thread_proposal_02",
    durationMs: 6,
    status: "success",
    health: "healthy",
    healthReason:
      "Signed execution lease lease_reply_20260527_002 (TTL 60s) (6ms).",
    provenance: "PLANNED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.919",
    completedAt: "10:40:00.925",
    spanId: "spn_auth_reply_002",
    previousLayer: "Layer 9 — Policy / Safety",
    nextLayer: "Layer 11 — Planning",
    inputContract: "PolicyDecisionEnvelope",
    outputContract: "SignedExecutionLease (Scope: gmail.send, Thread Bound)",
    owns: [
      "Cryptographic token signing",
      "Capability boundary enforcement",
      "Lease expiry calculation",
    ],
    doesNotOwn: ["Tool execution", "Model prompt generation"],
    internalFlow: [
      { step: "Capability token creation", durationMs: 3.1 },
      { step: "HMAC signature generation", durationMs: 2.9 },
    ],
    inputData: {
      policyDecision: "ALLOW_WITH_AUDIT",
      targetAction: "gmail.send_reply",
      threadId: "thread_proposal_02",
    },
    outputData: {
      leaseId: "lease_reply_20260527_002",
      authorizedScope: "gmail.send",
      boundThreadId: "thread_proposal_02",
      boundRecipient: "john.doe@partner.org",
      expiresAt: "2026-05-27T10:41:00.925Z",
      ttlSeconds: 60,
      signature: "hmac_sha256_88b91a2c3d4e5f60...",
    },
    contractDiff: [
      {
        field: "leaseId",
        type: "ADDED",
        outputValue: "lease_reply_20260527_002",
        note: "Lease created",
      },
      {
        field: "ttlSeconds",
        type: "ADDED",
        outputValue: "60",
        note: "Time bound",
      },
    ],
    expectedVsActual: {
      expected: "SignedExecutionLease with valid cryptographic signature",
      actual: "SignedExecutionLease (lease_reply_20260527_002, 60s TTL)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "PolicyDecisionEnvelope",
        fromType: "DERIVED",
        transform: "HMAC Capability Token Signer",
        to: "SignedExecutionLease",
        toType: "DERIVED",
        destination: "Layer 11 — Planning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Lease Signature Valid",
        description: "HMAC SHA256 verified",
        status: "PASS",
      },
      {
        checkName: "Scoped to Specific Thread",
        description: "Constrained strictly to thread_proposal_02",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Token Creation", durationMs: 3.1, percentage: 51.7 },
      { operation: "HMAC Signature", durationMs: 2.9, percentage: 48.3 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.4,
      heapDeltaKb: 2.5,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 7.8,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.924",
        level: "INFO",
        event: "auth.lease_signed",
        metadata: "Signed lease lease_reply_20260527_002 (TTL 60s)",
      },
    ],
    rawJson: {
      leaseId: "lease_reply_20260527_002",
      scope: "gmail.send",
      ttl: 60,
    },
  },
  {
    id: 11,
    name: "Planning",
    layerKey: "planning",
    responsibility:
      "Construct ordered DAG execution plan with idempotency keys",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason:
      "Constructed 2-step plan: Send Email Reply -> Create Calendar Hold (4ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.925",
    completedAt: "10:40:00.929",
    spanId: "spn_plan_reply_002",
    previousLayer: "Layer 10 — Authorization",
    nextLayer: "Layer 12 — Durable Execution",
    inputContract: "SignedExecutionLease",
    outputContract: "ExecutablePlanGraph (2 Steps + Idempotency Keys)",
    owns: [
      "Plan DAG generation",
      "Idempotency key assignment",
      "Precondition validation",
    ],
    doesNotOwn: ["Granting authorization", "Executing network calls"],
    internalFlow: [
      { step: "DAG step sequencing", durationMs: 2.2 },
      { step: "Idempotency key assignment", durationMs: 1.8 },
    ],
    inputData: {
      leaseId: "lease_reply_20260527_002",
    },
    outputData: {
      planId: "plan_reply_002",
      steps: [
        {
          stepIndex: 1,
          action: "gmail.send_reply",
          idempotencyKey: "idemp_reply_john_02",
          retryPolicy: "max_2_exponential",
        },
        {
          stepIndex: 2,
          action: "calendar.create_tentative_hold",
          idempotencyKey: "idemp_cal_hold_002",
          retryPolicy: "max_2_exponential",
        },
      ],
      totalSteps: 2,
    },
    contractDiff: [
      {
        field: "planId",
        type: "ADDED",
        outputValue: "plan_reply_002",
        note: "Plan compiled",
      },
      { field: "stepsCount", type: "ADDED", outputValue: "2", note: "2 steps" },
    ],
    expectedVsActual: {
      expected: "ExecutablePlanGraph with ordered idempotent steps",
      actual: "ExecutablePlanGraph (2 steps: Send Reply, Hold Calendar)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "SignedExecutionLease",
        fromType: "DERIVED",
        transform: "DAG Plan Compiler",
        to: "ExecutablePlanGraph",
        toType: "DERIVED",
        destination: "Layer 12 — Durable Execution",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Idempotency Keys Unique",
        description: "idemp_reply_john_02 uniquely hashed",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Step Sequencing", durationMs: 2.2, percentage: 55.0 },
      { operation: "Idempotency Keying", durationMs: 1.8, percentage: 45.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.9,
      heapDeltaKb: 2.0,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.1,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.928",
        level: "INFO",
        event: "plan.compiled",
        metadata: "Plan plan_reply_002 generated (2 steps)",
      },
    ],
    rawJson: { planId: "plan_reply_002", steps: 2 },
  },
  {
    id: 12,
    name: "Durable Execution",
    layerKey: "durable_execution",
    responsibility:
      "Claim execution lock, assign worker, and prepare crash-recovery checkpoint",
    durationMs: 7,
    status: "success",
    health: "healthy",
    healthReason: "Claimed worker lease claim_reply_002_wk1 (7ms).",
    provenance: "PLANNED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.929",
    completedAt: "10:40:00.936",
    spanId: "spn_dur_reply_002",
    previousLayer: "Layer 11 — Planning",
    nextLayer: "Layer 13 — Tool / Adapter Action",
    inputContract: "ExecutablePlanGraph",
    outputContract: "DurableExecutionClaim (Claim ID: claim_reply_002_wk1)",
    owns: [
      "Distributed lock acquisition",
      "Worker claim management",
      "Crash-recovery checkpointing",
    ],
    doesNotOwn: ["Tool API execution", "AI generation"],
    internalFlow: [
      { step: "PostgreSQL lease row claim", durationMs: 4.1 },
      { step: "Heartbeat registration", durationMs: 2.9 },
    ],
    inputData: {
      planId: "plan_reply_002",
      idempotencyKey: "idemp_reply_john_02",
    },
    outputData: {
      claimId: "claim_reply_002_wk1",
      workerId: "worker_core_01",
      lockState: "LOCKED_ACTIVE",
      checkpointRecorded: true,
    },
    contractDiff: [
      {
        field: "claimId",
        type: "ADDED",
        outputValue: "claim_reply_002_wk1",
        note: "Lock active",
      },
    ],
    expectedVsActual: {
      expected: "DurableExecutionClaim with active worker lock",
      actual:
        "DurableExecutionClaim (claim_reply_002_wk1 locked to worker_core_01)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "ExecutablePlanGraph",
        fromType: "DERIVED",
        transform: "PostgreSQL Row Lock Claim",
        to: "DurableExecutionClaim",
        toType: "DERIVED",
        destination: "Layer 13 — Tool / Adapter Action",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Lock Exclusive",
        description: "Zero competing workers hold lease",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "PostgreSQL Row Lock", durationMs: 4.1, percentage: 58.6 },
      { operation: "Heartbeat Init", durationMs: 2.9, percentage: 41.4 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.3,
      heapDeltaKb: 2.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 7.9,
    },
    layerLogs: [
      {
        timestamp: "10:40:00.934",
        level: "INFO",
        event: "durable.claimed",
        metadata: "Worker worker_core_01 locked claim_reply_002_wk1",
      },
    ],
    rawJson: { claimId: "claim_reply_002_wk1", worker: "worker_core_01" },
  },
  {
    id: 13,
    name: "Tool / Adapter Action",
    layerKey: "tool_action",
    responsibility: "Invoke Gmail REST API to send the RFC 2822 reply email",
    durationMs: 812,
    status: "success",
    health: "healthy",
    healthReason:
      "Gmail API POST /messages/send returned HTTP 200 (msg_reply_9981_sent) (812ms).",
    provenance: "SIMULATED",
    isCriticalPath: true,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:00.936",
    completedAt: "10:40:01.748",
    spanId: "spn_tool_reply_002",
    previousLayer: "Layer 12 — Durable Execution",
    nextLayer: "Layer 14 — Observation",
    inputContract: "DurableExecutionClaim (Action: gmail.send_reply)",
    outputContract: "RawToolHttpResponse (Gmail API HTTP 200)",
    owns: ["External OAuth2 REST call", "RFC 2822 MIME payload transmission"],
    doesNotOwn: ["Permission decisions", "Verification assertions"],
    internalFlow: [
      { step: "MIME payload encoding", durationMs: 14.0 },
      { step: "Gmail API HTTPS POST", durationMs: 782.0 },
      { step: "Response header capture", durationMs: 16.0 },
    ],
    inputData: {
      provider: "Google Gmail REST API",
      endpoint:
        "POST https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
      headers: {
        Authorization: "Bearer ya29.mock_oauth2_token",
        "Content-Type": "application/json",
      },
      to: "John Doe <john.doe@partner.org>",
      threadId: "thread_proposal_02",
      inReplyTo: "<proposal-followup-20260527@partner.org>",
      subject: "Re: Proposal follow-up for Q3 Architecture",
    },
    outputData: {
      httpStatus: 200,
      sentMessageId: "msg_reply_9981_sent",
      threadId: "thread_proposal_02",
      labelIds: ["SENT", "INBOX"],
      deliveredAt: "2026-05-27T10:40:01.748Z",
    },
    contractDiff: [
      {
        field: "sentMessageId",
        type: "ADDED",
        outputValue: "msg_reply_9981_sent",
        note: "Sent ID returned",
      },
      {
        field: "httpStatus",
        type: "ADDED",
        outputValue: "200",
        note: "Success status",
      },
    ],
    expectedVsActual: {
      expected: "RawToolHttpResponse with HTTP 200 and sentMessageId",
      actual:
        "RawToolHttpResponse (HTTP 200, sentMessageId: msg_reply_9981_sent)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "DurableExecutionClaim",
        fromType: "DERIVED",
        transform: "Gmail REST API Client",
        to: "RawToolHttpResponse (msg_reply_9981_sent)",
        toType: "DERIVED",
        destination: "Layer 14 — Observation",
      },
    ],
    evidenceChecks: [
      {
        checkName: "HTTP 200 OK",
        description: "Gmail API accepted and delivered message",
        status: "PASS",
      },
      {
        checkName: "Valid Thread ID Preserved",
        description: "Message appended to thread_proposal_02",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "MIME Encoding", durationMs: 14.0, percentage: 1.7 },
      {
        operation: "Gmail API Network Call",
        durationMs: 782.0,
        percentage: 96.3,
      },
      { operation: "Response Capture", durationMs: 16.0, percentage: 2.0 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 6.2,
      heapDeltaKb: 14.0,
      eventLoopLagMs: 0.03,
      memoryAllocatedKb: 48.0,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.740",
        level: "INFO",
        event: "tool.sent",
        metadata: "Sent reply msg_reply_9981_sent to John Doe via Gmail API",
      },
    ],
    rawJson: { status: 200, sentMessageId: "msg_reply_9981_sent" },
  },
  {
    id: 14,
    name: "Observation",
    layerKey: "observation",
    responsibility:
      "Capture raw HTTP response into an immutable cryptographic observation record",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason:
      "Recorded observation record with SHA-256 payload hash (4ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:01.748",
    completedAt: "10:40:01.752",
    spanId: "spn_obs_reply_002",
    previousLayer: "Layer 13 — Tool / Adapter Action",
    nextLayer: "Layer 15 — Verification",
    inputContract: "RawToolHttpResponse",
    outputContract: "ImmutableObservationRecord (SHA-256 Verified)",
    owns: ["Cryptographic payload hashing", "Immutable snapshot recording"],
    doesNotOwn: ["Verification assertions", "Reward calculation"],
    internalFlow: [
      { step: "SHA-256 response hashing", durationMs: 2.1 },
      { step: "Observation record storage", durationMs: 1.9 },
    ],
    inputData: {
      sentMessageId: "msg_reply_9981_sent",
      threadId: "thread_proposal_02",
      status: 200,
    },
    outputData: {
      observationId: "obs_reply_002",
      payloadHash: "sha256:7f81a9c3d4e5f601b2a3c4d5e6f70819...",
      recordedAt: "2026-05-27T10:40:01.750Z",
      deliveryConfirmed: true,
    },
    contractDiff: [
      {
        field: "observationId",
        type: "ADDED",
        outputValue: "obs_reply_002",
        note: "Observation recorded",
      },
      {
        field: "payloadHash",
        type: "ADDED",
        outputValue: "sha256:7f81a9...",
        note: "Hashed",
      },
    ],
    expectedVsActual: {
      expected: "ImmutableObservationRecord with SHA-256 hash",
      actual: "ImmutableObservationRecord (obs_reply_002, SHA-256 verified)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "RawToolHttpResponse",
        fromType: "OBSERVED",
        transform: "SHA-256 Observation Hashing",
        to: "ImmutableObservationRecord",
        toType: "DERIVED",
        destination: "Layer 15 — Verification",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Payload Integrity Verified",
        description: "SHA-256 hash computed cleanly",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "SHA-256 Hashing", durationMs: 2.1, percentage: 52.5 },
      { operation: "Snapshot Storage", durationMs: 1.9, percentage: 47.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.9,
      heapDeltaKb: 2.0,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.2,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.751",
        level: "INFO",
        event: "obs.recorded",
        metadata: "Recorded observation obs_reply_002",
      },
    ],
    rawJson: { observationId: "obs_reply_002", delivery: true },
  },
  {
    id: 15,
    name: "Verification",
    layerKey: "verification",
    responsibility:
      "Verify observed external delivery against expected criteria",
    durationMs: 6,
    status: "success",
    health: "healthy",
    healthReason:
      "6 / 6 Verification assertions passed (Status: VERIFIED) (6ms).",
    provenance: "DERIVED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:01.752",
    completedAt: "10:40:01.758",
    spanId: "spn_ver_reply_002",
    previousLayer: "Layer 14 — Observation",
    nextLayer: "Layer 16 — Reward",
    inputContract: "ImmutableObservationRecord + ExpectedDeliveryCriteria",
    outputContract: "VerificationResult (6/6 Assertions Passed)",
    owns: ["Deterministic assertion evaluation", "Discrepancy detection"],
    doesNotOwn: ["Reward generation", "Memory persistence"],
    internalFlow: [
      { step: "Assertion evaluation (6 checks)", durationMs: 3.5 },
      { step: "Verification verdict formulation", durationMs: 2.5 },
    ],
    inputData: {
      observationId: "obs_reply_002",
      expectedThread: "thread_proposal_02",
      expectedRecipient: "john.doe@partner.org",
    },
    outputData: {
      verificationStatus: "VERIFIED",
      assertionsPassed: 6,
      assertionsTotal: 6,
      details: [
        { assertion: "HTTP Response Status == 200", status: "PASS" },
        {
          assertion: "Delivered to Expected Recipient (john.doe@partner.org)",
          status: "PASS",
        },
        { assertion: "Thread ID Matches (thread_proposal_02)", status: "PASS" },
        { assertion: "RFC 2822 In-Reply-To Header Correct", status: "PASS" },
        { assertion: "Zero Duplicate Transmissions", status: "PASS" },
        { assertion: "Tentative Calendar Hold Queued", status: "PASS" },
      ],
    },
    contractDiff: [
      {
        field: "verificationStatus",
        type: "ADDED",
        outputValue: "VERIFIED",
        note: "Verified",
      },
      {
        field: "assertionsPassed",
        type: "ADDED",
        outputValue: "6 / 6",
        note: "All passed",
      },
    ],
    expectedVsActual: {
      expected: "VerificationResult with 6/6 passing assertions",
      actual: "VerificationResult (VERIFIED, 6/6 passed)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "ImmutableObservationRecord",
        fromType: "DERIVED",
        transform: "Assertion Engine",
        to: "VerificationResult (VERIFIED)",
        toType: "DERIVED",
        destination: "Layer 16 — Reward",
      },
    ],
    evidenceChecks: [
      {
        checkName: "All Assertions Passed",
        description: "6 / 6 assertions passed",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Assertion Evaluation", durationMs: 3.5, percentage: 58.3 },
      { operation: "Verdict Formulation", durationMs: 2.5, percentage: 41.7 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 1.1,
      heapDeltaKb: 2.3,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 6.8,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.757",
        level: "INFO",
        event: "verify.passed",
        metadata: "Verification passed (6/6 assertions)",
      },
    ],
    rawJson: { status: "VERIFIED", passed: 6, total: 6 },
  },
  {
    id: 16,
    name: "Reward",
    layerKey: "reward",
    responsibility:
      "Compute reward feedback signal based on verified task success, tone alignment, and speed",
    durationMs: 3,
    status: "success",
    health: "healthy",
    healthReason: "Calculated composite reward score: 0.94 (3ms).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:01.758",
    completedAt: "10:40:01.761",
    spanId: "spn_rew_reply_002",
    previousLayer: "Layer 15 — Verification",
    nextLayer: "Layer 17 — Learning",
    inputContract: "VerificationResult",
    outputContract: "RewardSignal (Composite Score: 0.94)",
    owns: ["Multi-objective reward weighting"],
    doesNotOwn: ["Overriding safety policies", "Granting authorization"],
    internalFlow: [
      { step: "Reward scoring computation", durationMs: 1.6 },
      { step: "Cost & latency penalization", durationMs: 1.4 },
    ],
    inputData: {
      verificationStatus: "VERIFIED",
      latencyMs: 1842,
      costUsd: 0.0004,
    },
    outputData: {
      compositeRewardScore: 0.94,
      subscores: {
        taskSuccess: 1.0,
        toneAlignment: 0.98,
        latencyScore: 0.91,
        costEfficiency: 0.96,
      },
    },
    contractDiff: [
      {
        field: "compositeRewardScore",
        type: "ADDED",
        outputValue: "0.94",
        note: "Reward calculated",
      },
    ],
    expectedVsActual: {
      expected: "RewardSignal with composite score >= 0.85",
      actual: "RewardSignal (0.94 score, toneAlignment 0.98)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "VerificationResult",
        fromType: "DERIVED",
        transform: "Reward Function",
        to: "RewardSignal (0.94)",
        toType: "DERIVED",
        destination: "Layer 17 — Learning",
      },
    ],
    evidenceChecks: [
      {
        checkName: "High Task Reward",
        description: "Composite score 0.94 above target",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Reward Scoring", durationMs: 1.6, percentage: 53.3 },
      { operation: "Penalty Calculation", durationMs: 1.4, percentage: 46.7 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.8,
      heapDeltaKb: 1.7,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 5.2,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.760",
        level: "INFO",
        event: "reward.computed",
        metadata: "Composite reward: 0.94",
      },
    ],
    rawJson: { score: 0.94, taskSuccess: 1.0 },
  },
  {
    id: 17,
    name: "Learning",
    layerKey: "learning",
    responsibility:
      "Update routing weights and candidate ranking priors for partner meeting auto-replies",
    durationMs: 4,
    status: "success",
    health: "healthy",
    healthReason: "Updated partner meeting scheduling prior +0.03 (4ms).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:01.761",
    completedAt: "10:40:01.765",
    spanId: "spn_learn_reply_002",
    previousLayer: "Layer 16 — Reward",
    nextLayer: "Layer 18 — Verified Memory",
    inputContract: "RewardSignal + VerificationResult",
    outputContract: "LearningUpdate (Partner Meeting Prior Weight Delta +0.03)",
    owns: ["Prior weight adjustments", "Ranking calibrations"],
    doesNotOwn: ["Modifying safety policy", "Granting permissions"],
    internalFlow: [
      { step: "Prior delta calculation", durationMs: 2.1 },
      { step: "Routing weight update", durationMs: 1.9 },
    ],
    inputData: {
      compositeRewardScore: 0.94,
    },
    outputData: {
      priorUpdated: "PARTNER_MEETING_SCHEDULING_PRIOR",
      delta: 0.03,
      newWeight: 0.91,
    },
    contractDiff: [
      {
        field: "priorDelta",
        type: "ADDED",
        outputValue: "+0.03",
        note: "Weight increased",
      },
    ],
    expectedVsActual: {
      expected: "LearningUpdate with non-zero positive prior delta",
      actual: "LearningUpdate (delta: +0.03 for partner meeting prior)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "RewardSignal",
        fromType: "DERIVED",
        transform: "Prior Calibration Engine",
        to: "LearningUpdate",
        toType: "DERIVED",
        destination: "Layer 18 — Verified Memory",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Safety Policy Untouched",
        description: "Learning did not alter safety invariants",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Delta Calculation", durationMs: 2.1, percentage: 52.5 },
      { operation: "Weight Update", durationMs: 1.9, percentage: 47.5 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 0.9,
      heapDeltaKb: 1.8,
      eventLoopLagMs: 0.01,
      memoryAllocatedKb: 5.5,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.764",
        level: "INFO",
        event: "learning.updated",
        metadata: "Updated scheduling prior (+0.03)",
      },
    ],
    rawJson: { prior: "PARTNER_MEETING_SCHEDULING", delta: 0.03 },
  },
  {
    id: 18,
    name: "Verified Memory",
    layerKey: "verified_memory",
    responsibility:
      "Persist verified interaction record (#MEM-00130) to durable pgvector knowledge store",
    durationMs: 18,
    status: "success",
    health: "healthy",
    healthReason:
      "Persisted #MEM-00130 (Confirmed Thursday 2 PM Sync with John Doe) (18ms).",
    provenance: "SIMULATED",
    isCriticalPath: false,
    warningsCount: 0,
    errorsCount: 0,
    attempts: "1 / 1",
    retryCount: 0,
    startedAt: "10:40:01.765",
    completedAt: "10:40:01.783",
    spanId: "spn_vmem_reply_002",
    previousLayer: "Layer 17 — Learning",
    nextLayer: "★ Final Result",
    inputContract: "LearningUpdate + VerificationResult",
    outputContract: "VerifiedMemoryWriteResult (Memory ID: #MEM-00130)",
    owns: [
      "Durable pgvector write",
      "Memory deduplication",
      "Retention policy tagging",
    ],
    doesNotOwn: ["Granting runtime authorization"],
    internalFlow: [
      { step: "Knowledge vector embedding", durationMs: 9.2 },
      { step: "pgvector insert & HNSW indexing", durationMs: 8.8 },
    ],
    inputData: {
      memoryContent:
        "Confirmed 15-minute architecture proposal meeting with John Doe for Thursday, May 29, 2026 at 2:00 PM (Asia/Manila).",
      verificationStatus: "VERIFIED",
    },
    outputData: {
      memoryId: "MEM_00130",
      storedType: "INTERACTION_EVENT",
      status: "STORED",
      retention: "PERMANENT",
      indexedVectorDim: 768,
    },
    contractDiff: [
      {
        field: "memoryId",
        type: "ADDED",
        outputValue: "MEM_00130",
        note: "Memory stored",
      },
      {
        field: "status",
        type: "ADDED",
        outputValue: "STORED",
        note: "Persisted",
      },
    ],
    expectedVsActual: {
      expected: "VerifiedMemoryWriteResult with STORED status",
      actual: "VerifiedMemoryWriteResult (MEM_00130, STORED in pgvector)",
      matchStatus: "MATCH",
    },
    dataLineage: [
      {
        from: "VerificationResult + LearningUpdate",
        fromType: "DERIVED",
        transform: "pgvector Store",
        to: "VerifiedMemoryWriteResult (MEM_00130)",
        toType: "DERIVED",
        destination: "★ Final Result",
      },
    ],
    evidenceChecks: [
      {
        checkName: "Memory Verified Before Write",
        description: "Passed 6/6 verification checks",
        status: "PASS",
      },
    ],
    timingWaterfall: [
      { operation: "Embedding Generation", durationMs: 9.2, percentage: 51.1 },
      { operation: "pgvector Index Insert", durationMs: 8.8, percentage: 48.9 },
    ],
    mockTelemetry: {
      cpuUserTimeMs: 2.8,
      heapDeltaKb: 6.4,
      eventLoopLagMs: 0.02,
      memoryAllocatedKb: 21.0,
    },
    layerLogs: [
      {
        timestamp: "10:40:01.780",
        level: "INFO",
        event: "memory.stored",
        metadata: "Persisted #MEM-00130 to verified knowledge store",
      },
    ],
    rawJson: { memoryId: "MEM_00130", status: "STORED" },
  },
];
