export const RUN_METADATA_ASK_2 = {
  runId: "run_20260527_reply_002",
  goal: "Auto-reply to John Doe on Gmail proposing Thursday 2:00 PM sync (Acting as Nelson).",
  status: "Completed (Verified & Sent)",
  statusColor: "emerald",
  mode: "Personal Digital Assistant (Acting as Me)",
  duration: "1.842s",
  durationMs: 1842,
  startedAt: "2026-05-27 10:40:00 UTC",
  totalLayers: 18,
  passedLayers: 18,
  failedLayers: 0,
  skippedLayers: 0,
  policyViolations: 0,
  evalAssertionsPassed: "6 / 6",
  activeLease: "lease_reply_20260527_002 (TTL: 60s)",
  provenance: "OBSERVED (Client-side Simulation)",
  traceId: "trc_autodo_20260527_reply_02",
  currentAttempt: "1 of 3",
  isDurable: true,
  workerId: "worker_core_01",
  estimatedCostUsd: 0.0004,
  tokenUsage: { prompt: 580, completion: 245, total: 825 },
  sourceSystem: "Gmail",
  provider: "Google Gmail API v1",
  origin: "gmail.googleapis.com",
} as const;
