import type { LocalDevSecret } from "../contracts";

export const RUNTIME_INFO = {
  environment: "development (local personal client prototype)",
  appVersion: "AutoDo 01-v2 v0.1.0 (package.json)",
  nextVersion: "16.3.3 (package.json)",
  reactVersion: "19.2.8 (package.json)",
  nodeVersion: "v20+ (Server Runtime [PLANNED / MOCK])",
  typescriptVersion: "5.x (package.json)",
  tailwindVersion: "4.x (package.json)",
  databaseEngine:
    "PostgreSQL 16 + Drizzle + pgvector (Target Architecture [PLANNED])",
  aiProviderTarget: "Google Gemini 2.5 Pro (Target JSON Mode [SIMULATED])",
  mcpProtocolVersion: "2024-11-05 (MCP Protocol Spec [SIMULATED])",
};

export const LOCAL_DEV_SECRETS: readonly LocalDevSecret[] = [
  {
    id: "sec_gemini",
    label: "Gemini API Key",
    maskedValue: "AIza••••••••••••••••••••••••",
    mockValue: "LOCALDEV_GEMINI_KEY_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "gemini-2.5-pro:generateContent",
    lastLoaded: "2026-05-27 10:32:11 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_gmail_acc",
    label: "Gmail OAuth Access Token",
    maskedValue: "ya29.•••••••••••••••••••••••",
    mockValue: "LOCALDEV_GMAIL_ACCESS_TOKEN_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "https://www.googleapis.com/auth/gmail.readonly",
    lastLoaded: "2026-05-27 10:32:12 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_gmail_ref",
    label: "Gmail OAuth Refresh Token",
    maskedValue: "1//04•••••••••••••••••••••••",
    mockValue: "LOCALDEV_GMAIL_REFRESH_TOKEN_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "offline_access",
    lastLoaded: "2026-05-27 10:00:00 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_client_id",
    label: "Google OAuth Client ID",
    maskedValue: "9812••••••••.apps.googleusercontent.com",
    mockValue: "LOCALDEV_CLIENT_ID_AUTODO_V1.apps.googleusercontent.com",
    source: ".env.local (MOCK)",
    scope: "client_credentials",
    lastLoaded: "2026-05-27 10:00:00 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_client_sec",
    label: "Google OAuth Client Secret",
    maskedValue: "GOCSPX-•••••••••••••••••••••",
    mockValue: "LOCALDEV_CLIENT_SECRET_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "client_credentials",
    lastLoaded: "2026-05-27 10:00:00 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_session",
    label: "Developer Session Token",
    maskedValue: "ses_••••••••••••••••••••••••",
    mockValue: "LOCALDEV_SESSION_TOKEN_AUTODO_V1",
    source: "Session Storage (MOCK)",
    scope: "workspace:admin",
    lastLoaded: "2026-05-27 10:32:11 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_webhook",
    label: "Webhook Secret",
    maskedValue: "whsec_••••••••••••••••••••••",
    mockValue: "LOCALDEV_WEBHOOK_SECRET_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "ingress:verify",
    lastLoaded: "2026-05-27 10:32:11 AM",
    status: "Active (Local Mock)",
  },
  {
    id: "sec_enc_key",
    label: "Encryption Key (AES-256)",
    maskedValue: "aes256_•••••••••••••••••••••",
    mockValue: "LOCALDEV_ENCRYPTION_KEY_AES256_AUTODO_V1",
    source: ".env.local (MOCK)",
    scope: "vault:encrypt",
    lastLoaded: "2026-05-27 10:00:00 AM",
    status: "Active (Local Mock)",
  },
];
