import type { CandidateAction, ModelProviderId } from "../contracts";

export const MODEL_OPTIONS_BY_PROVIDER: Record<
  ModelProviderId,
  readonly { readonly id: string; readonly label: string }[]
> = {
  nvidia: [
    {
      id: "openai/gpt-oss-120b",
      label: "GPT-OSS 120B (NVIDIA NIM - Frontier)",
    },
    {
      id: "openai/gpt-oss-20b",
      label: "GPT-OSS 20B (NVIDIA NIM)",
    },
    {
      id: "deepseek-ai/deepseek-v4-pro-0813",
      label: "DeepSeek v4 Pro (NVIDIA NIM)",
    },
    { id: "meta/llama-guard-4-12b", label: "Llama Guard 4 12B (NVIDIA NIM)" },
    {
      id: "nvidia/riva-translate-4b-instruct-v2",
      label: "Riva Translate 4B (NVIDIA NIM)",
    },
  ],
  gemini: [
    { id: "gemini-2.5-pro", label: "Gemini 2.5 Pro" },
    { id: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
  ],
  openai: [
    { id: "gpt-5", label: "GPT-5" },
    { id: "gpt-4o", label: "GPT-4o" },
  ],
  ollama: [
    { id: "llama-3.3-70b", label: "Llama 3.3 70B (Local)" },
    { id: "qwen-2.5-32b", label: "Qwen 2.5 32B (Local)" },
  ],
};

export const CANDIDATES: readonly CandidateAction[] = [
  {
    id: "c1",
    action: "gmail.list_messages",
    tool: "Gmail API",
    argumentsPayload: {
      query: "is:unread is:important newer_than:1d",
      maxResults: 10,
    },
    score: 0.94,
    qualityScore: 0.96,
    relevanceScore: 0.95,
    evidenceScore: 0.92,
    riskPenalty: 0.0,
    latencyEstimateMs: 580,
    costEstimateUsd: 0.0001,
    preferenceScore: 0.95,
    confidence: 0.96,
    status: "chosen",
    reason:
      "Best match for reading and listing unread important emails without pulling excessive message bodies.",
    requiredScope: "gmail.readonly",
    risk: "LOW",
  },
  {
    id: "c2",
    action: "gmail.search_messages",
    tool: "Gmail API",
    argumentsPayload: { q: "label:unread label:important" },
    score: 0.82,
    qualityScore: 0.85,
    relevanceScore: 0.88,
    evidenceScore: 0.9,
    riskPenalty: 0.05,
    latencyEstimateMs: 950,
    costEstimateUsd: 0.0002,
    preferenceScore: 0.8,
    confidence: 0.85,
    status: "rejected",
    reason:
      "Full-text mailbox search query is broader than required for inbox listing.",
    requiredScope: "gmail.readonly",
    risk: "LOW",
  },
  {
    id: "c3",
    action: "gmail.get_message",
    tool: "Gmail API",
    argumentsPayload: { id: "individual_batch" },
    score: 0.68,
    qualityScore: 0.72,
    relevanceScore: 0.7,
    evidenceScore: 0.8,
    riskPenalty: 0.1,
    latencyEstimateMs: 1800,
    costEstimateUsd: 0.0005,
    preferenceScore: 0.65,
    confidence: 0.7,
    status: "rejected",
    reason:
      "Requires retrieving full message bodies individually, adding unnecessary network roundtrips.",
    requiredScope: "gmail.readonly",
    risk: "LOW",
  },
  {
    id: "c4",
    action: "gmail.draft_reply",
    tool: "Gmail API",
    argumentsPayload: { threadId: "any", body: "Draft acknowledgment" },
    score: 0.45,
    qualityScore: 0.5,
    relevanceScore: 0.4,
    evidenceScore: 0.6,
    riskPenalty: 0.25,
    latencyEstimateMs: 650,
    costEstimateUsd: 0.0003,
    preferenceScore: 0.3,
    confidence: 0.5,
    status: "rejected",
    reason:
      "Mutates external state by creating drafts unrequested by the user prompt.",
    requiredScope: "gmail.modify",
    risk: "MEDIUM",
  },
];

export const CANDIDATES_ASK_2: readonly CandidateAction[] = [
  {
    id: "c_reply_1",
    action: "gmail.send_reply",
    tool: "Gmail API",
    argumentsPayload: {
      threadId: "thread_proposal_02",
      to: "john.doe@partner.org",
      proposedMeeting: "2026-05-29T14:00:00+08:00",
      signoff: "Best, Nelson",
    },
    score: 0.97,
    qualityScore: 0.98,
    relevanceScore: 0.99,
    evidenceScore: 0.96,
    riskPenalty: 0.0,
    latencyEstimateMs: 820,
    costEstimateUsd: 0.0002,
    preferenceScore: 0.98,
    confidence: 0.97,
    status: "chosen",
    reason:
      "Direct response in Nelson's professional tone proposing confirmed open slot (Thursday 2:00 PM) with verified trusted partner policy.",
    requiredScope: "gmail.send",
    risk: "MEDIUM",
  },
  {
    id: "c_reply_2",
    action: "gmail.create_draft",
    tool: "Gmail API",
    argumentsPayload: {
      threadId: "thread_proposal_02",
      to: "john.doe@partner.org",
    },
    score: 0.85,
    qualityScore: 0.9,
    relevanceScore: 0.88,
    evidenceScore: 0.92,
    riskPenalty: 0.05,
    latencyEstimateMs: 650,
    costEstimateUsd: 0.0002,
    preferenceScore: 0.82,
    confidence: 0.88,
    status: "rejected",
    reason:
      "Creates draft only, delaying partner communication when auto-reply policy is pre-authorized.",
    requiredScope: "gmail.modify",
    risk: "LOW",
  },
  {
    id: "c_reply_3",
    action: "slack.post_notification",
    tool: "Slack Webhook",
    argumentsPayload: { channel: "#general", text: "John Doe asked for call" },
    score: 0.52,
    qualityScore: 0.6,
    relevanceScore: 0.5,
    evidenceScore: 0.7,
    riskPenalty: 0.2,
    latencyEstimateMs: 400,
    costEstimateUsd: 0.0001,
    preferenceScore: 0.4,
    confidence: 0.6,
    status: "rejected",
    reason:
      "Mismatched communication channel; client reached out on Gmail email thread.",
    requiredScope: "slack.write",
    risk: "LOW",
  },
];
